### ISSUE TITLE
Segmentation error in terraform-ls

### ISSUE THREAD

**Issue by nanasess** [manateelazycat/lsp-bridge#1025]
1. Extract terraform-ls to the PATH location.
2. Apply the following patch to terraform-ls, which requires the `serve` argument.
```diff
diff --git a/langserver/terraform-ls.json b/langserver/terraform-ls.json
index 56c2768..9f77566 100644
--- a/langserver/terraform-ls.json
+++ b/langserver/terraform-ls.json
@@ -2,7 +2,8 @@
   "name": "terraform-ls",
   "languageId": "terraform",
   "command": [
-    "terraform-ls"
+    "terraform-ls",
+    "serve"
   ],
   "settings": {}
 }
```
3. When you open the `*.tf` file, you will get the following error
```
Start lsp server (terraform-ls) for /home/users/git-repos/example-terraform
2024/08/29 00:55:01 serve_command.go:108: Starting terraform-ls 0.35.0-beta1
2024/08/29 00:55:01 service.go:116: Preparing new session ...
2024/08/29 00:55:01 langserver.go:102: Starting server (pid 1393208; concurrency: 16) ...
2024/08/29 00:55:01 opts.go:215: Received request batch of size 1 (qlen=0)
2024/08/29 00:55:01 opts.go:215: Dequeued request batch of length 1 (qlen=0)

--- [00:55:01.826711] Send initialize request (50039) to 'terraform-ls' for project example-terraform
2024/08/29 00:55:01 opts.go:215: Request check error for "initialize" (params "{\"processId\": 1393169, \"rootPath\": \"/home/users/git-repos/example-terraform\", \"clientInfo\": {\"name\": \"emacs\", \"version\": \"lsp-bridge\"}, \"rootUri\": \"file:///home/users/git-repos/example-terraform\", \"capabilities\": {\"workspace\": {\"configuration\": true, \"symbol\": {\"resolveSupport\": {\"properties\": []}}}, \"textDocument\": {\"completion\": {\"completionItem\": {\"snippetSupport\": true, \"deprecatedSupport\": true, \"tagSupport\": {\"valueSet\": [1]}, \"resolveSupport\": {\"properties\": [\"documentation\", \"detail\", \"additionalTextEdits\"]}}}, \"codeAction\": {\"dynamicRegistration\": false, \"codeActionLiteralSupport\": {\"codeActionKind\": {\"valueSet\": [\"quickfix\", \"refactor\", \"refactor.extract\", \"refactor.inline\", \"refactor.rewrite\", \"source\", \"source.organizeImports\"]}}, \"isPreferredSupport\": true}, \"inlayHint\": {\"dynamicRegistration\": false}, \"diagnostic\": {\"dynamicRegistration\": true, \"relatedDocumentSupport\": true}, \"publishDiagnostics\": {\"relatedInformation\": true, \"tagSupport\": {\"valueSet\": [1, 2]}, \"versionSupport\": true, \"codeDescriptionSupport\": true, \"dataSupport\": true}}, \"window\": {\"workDoneProgress\": true}}, \"initializationOptions\": {}}"): [-32600] extra fields in request
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x9d66a8]

goroutine 33 [running]:
github.com/creachadair/jrpc2.InboundRequest(...)
	github.com/creachadair/jrpc2@v1.2.0/ctx.go:18
github.com/hashicorp/terraform-ls/internal/langserver.(*rpcLogger).LogResponse(0xc0002ea090, {0x0?, 0x0?}, 0xc000240100)
	github.com/hashicorp/terraform-ls/internal/langserver/rpc_logger.go:42 +0xc8
github.com/creachadair/jrpc2.tasks.responses({0xc000128218, 0x1, 0x0?}, {0x1b41b20, 0xc0002ea090})
	github.com/creachadair/jrpc2@v1.2.0/server.go:813 +0x439
github.com/creachadair/jrpc2.(*Server).dispatchLocked.func1()
	github.com/creachadair/jrpc2@v1.2.0/server.go:278 +0x229
github.com/creachadair/jrpc2.(*Server).serve.func1()
	github.com/creachadair/jrpc2@v1.2.0/server.go:180 +0x52
created by github.com/creachadair/jrpc2.(*Server).serve in goroutine 20
	github.com/creachadair/jrpc2@v1.2.0/server.go:178 +0x26

--- [00:55:01.853836] LSP server 'terraform-ls' exited with code 2
```
Since the same version of terraform-ls is running on VSCode, it may be a problem with lsp-bridge.
For your reference, here is the log of opening a `*.tf` file in VSCode.
```
Launching language server: /home/users/.vscode-server-insiders/extensions/hashicorp.terraform-2.33.2024082314-linux-x64/bin/terraform-ls serve
Client: Stopped --> Starting
2024/08/28 11:10:14 serve_command.go:108: Starting terraform-ls 0.35.0-beta1
2024/08/28 11:10:14 service.go:116: Preparing new session ...
2024/08/28 11:10:14 langserver.go:102: Starting server (pid 1097382; concurrency: 16) ...
2024/08/28 11:10:14 opts.go:215: Received request batch of size 1 (qlen=0)
2024/08/28 11:10:14 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/08/28 11:10:14 rpc_logger.go:32: Incoming request for "initialize" (ID 0): {"processId":1097080,"clientInfo":{"name":"Visual Studio Code - Insiders","version":"1.93.0-insider"},"locale":"en","rootPath":"/home/users/git-repos/example-terraform","rootUri":"file:///home/users/git-repos/example-terraform","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"changeAnnotationSupport":{"groupsOnLabel":true}},"configuration":true,"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]},"resolveSupport":{"properties":["location.range"]}},"codeLens":{"refreshSupport":true},"executeCommand":{"dynamicRegistration":true},"didChangeConfiguration":{"dynamicRegistration":true},"workspaceFolders":true,"foldingRange":{"refreshSupport":true},"semanticTokens":{"refreshSupport":true},"fileOperations":{"dynamicRegistration":true,"didCreate":true,"didRename":true,"didDelete":true,"willCreate":true,"willRename":true,"willDelete":true},"inlineValue":{"refreshSupport":true},"inlayHint":{"refreshSupport":true},"diagnostics":{"refreshSupport":true}},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]},"codeDescriptionSupport":true,"dataSupport":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]},"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true},"insertTextMode":2,"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"completionList":{"itemDefaults":["commitCharacters","editRange","insertTextFormat","insertTextMode","data"]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true},"activeParameterSupport":true},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true,"tagSupport":{"valueSet":[1]},"labelSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"disabledSupport":true,"dataSupport":true,"resolveSupport":{"properties":["edit"]},"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"honorsChangeAnnotations":true},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true,"rangesSupport":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1,"honorsChangeAnnotations":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true,"foldingRangeKind":{"valueSet":["comment","imports","region"]},"foldingRange":{"collapsedText":false}},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true},"callHierarchy":{"dynamicRegistration":true},"semanticTokens":{"dynamicRegistration":true,"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator","decorator","hcl-attrName","hcl-blockType","hcl-blockLabel","hcl-bool","hcl-string","hcl-number","hcl-objectKey","hcl-mapKey","hcl-keyword","hcl-referenceStep","hcl-typeComplex","hcl-typePrimitive","hcl-functionName"],"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary","hcl-dependent","terraform-data","terraform-locals","terraform-module","terraform-output","terraform-provider","terraform-resource","terraform-provisioner","terraform-connection","terraform-variable","terraform-terraform","terraform-backend","terraform-name","terraform-type","terraform-requiredProviders"],"formats":["relative"],"requests":{"range":true,"full":{"delta":true}},"multilineTokenSupport":false,"overlappingTokenSupport":false,"serverCancelSupport":true,"augmentsSyntaxTokens":true},"linkedEditingRange":{"dynamicRegistration":true},"typeHierarchy":{"dynamicRegistration":true},"inlineValue":{"dynamicRegistration":true},"inlayHint":{"dynamicRegistration":true,"resolveSupport":{"properties":["tooltip","textEdits","label.tooltip","label.location","label.command"]}},"diagnostic":{"dynamicRegistration":true,"relatedDocumentSupport":false}},"window":{"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"showDocument":{"support":true},"workDoneProgress":true},"general":{"staleRequestSupport":{"cancel":true,"retryOnContentModified":["textDocument/semanticTokens/full","textDocument/semanticTokens/range","textDocument/semanticTokens/full/delta"]},"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"markdown":{"parser":"marked","version":"1.1.0"},"positionEncodings":["utf-16"]},"notebookDocument":{"synchronization":{"dynamicRegistration":true,"executionSummarySupport":true}},"experimental":{"refreshModuleProvidersCommandId":"client.refreshModuleProviders","refreshModuleCallsCommandId":"client.refreshModuleCalls","telemetryVersion":1,"refreshTerraformVersionCommandId":"client.refreshTerraformVersion"}},"initializationOptions":{"validation":{"enableEnhancedValidation":true},"experimentalFeatures":{"validateOnSave":false,"prefillRequiredFields":false},"ignoreSingleFileWarning":false,"terraform":{"path":"","timeout":"","logFilePath":""},"indexing":{"ignorePaths":[],"ignoreDirectoryNames":[]}},"trace":"off","workspaceFolders":[{"uri":"file:///home/users/git-repos/example-terraform","name":"example-terraform"}],"workDoneToken":"9492ab56-d257-4168-8c1f-50f596eac62e"}
2024/08/28 11:10:14 initialize.go:185: enabling telemetry (version: 1)
2024/08/28 11:10:14 initialize.go:190: telemetry enabled (version: 1)
2024/08/28 11:10:14 scheduler.go:56: launching eval loop 0
2024/08/28 11:10:14 service.go:487: started low priority scheduler
2024/08/28 11:10:14 scheduler.go:56: launching eval loop 0
2024/08/28 11:10:14 service.go:492: started high priority scheduler
2024/08/28 11:10:14 discover.go:21: bus: "feature.rootmodules" subscribed to OnDiscover
2024/08/28 11:10:14 did_open.go:28: bus: "feature.rootmodules" subscribed to OnDidOpen
2024/08/28 11:10:14 manifest_change.go:23: bus: "feature.rootmodules" subscribed to OnManifestChange
2024/08/28 11:10:14 lockfile_change.go:23: bus: "feature.rootmodules" subscribed to OnPluginLockChange
2024/08/28 11:10:14 discover.go:21: bus: "feature.modules" subscribed to OnDiscover
2024/08/28 11:10:14 did_open.go:28: bus: "feature.modules" subscribed to OnDidOpen
2024/08/28 11:10:14 did_change.go:24: bus: "feature.modules" subscribed to OnDidChange
2024/08/28 11:10:14 did_change_watched.go:27: bus: "feature.modules" subscribed to OnDidChangeWatched
2024/08/28 11:10:14 discover.go:21: bus: "feature.variables" subscribed to OnDiscover
2024/08/28 11:10:14 did_open.go:28: bus: "feature.variables" subscribed to OnDidOpen
2024/08/28 11:10:14 did_change.go:24: bus: "feature.variables" subscribed to OnDidChange
2024/08/28 11:10:14 did_change_watched.go:27: bus: "feature.variables" subscribed to OnDidChangeWatched
2024/08/28 11:10:14 discover.go:21: bus: "feature.stacks" subscribed to OnDiscover
2024/08/28 11:10:14 did_open.go:28: bus: "feature.stacks" subscribed to OnDidOpen
2024/08/28 11:10:14 did_change.go:24: bus: "feature.stacks" subscribed to OnDidChange
2024/08/28 11:10:14 did_change_watched.go:27: bus: "feature.stacks" subscribed to OnDidChangeWatched
2024/08/28 11:10:14 opts.go:215: Posting server notification "telemetry/event" {"v":1,"name":"initialize","properties":{"experimentalCapabilities.referenceCountCodeLens":false,"experimentalCapabilities.refreshModuleCalls":true,"experimentalCapabilities.refreshModuleProviders":true,"experimentalCapabilities.refreshTerraformVersion":true,"lsVersion":"0.35.0-beta1","options.commandPrefix":false,"options.excludeModulePaths":false,"options.experimentalFeatures.prefillRequiredFields":false,"options.experimentalFeatures.validateOnSave":false,"options.ignoreSingleFileWarning":false,"options.indexing.ignoreDirectoryNames":false,"options.indexing.ignorePaths":false,"options.rootModulePaths":false,"options.terraform.logFilePath":false,"options.terraform.path":false,"options.terraform.timeout":"","options.validation.earlyValidation":true,"root_uri":"dir"}}
2024/08/28 11:10:14 walker_paths.go:255: walking next dir: {"file:///home/users/git-repos/example-terraform"}
2024/08/28 11:10:14 discover.go:26: bus: -> Discover /home/users/git-repos/example-terraform
2024/08/28 11:10:14 rpc_logger.go:53: Response to "initialize" (ID 0): {"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":[".","["],"resolveProvider":true},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"declarationProvider":true,"definitionProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["source.formatAll.terraform"]},"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"executeCommandProvider":{"commands":["terraform-ls.module.callers","terraform-ls.module.calls","terraform-ls.module.providers","terraform-ls.module.terraform","terraform-ls.rootmodules","terraform-ls.terraform.init","terraform-ls.terraform.validate"],"workDoneProgress":true},"semanticTokensProvider":{"legend":{"tokenTypes":["enumMember","function","keyword","number","parameter","property","string","type","variable","hcl-attrName","hcl-blockType","hcl-blockLabel","hcl-bool","hcl-string","hcl-number","hcl-objectKey","hcl-mapKey","hcl-keyword","hcl-referenceStep","hcl-typeComplex","hcl-typePrimitive","hcl-functionName"],"tokenModifiers":["defaultLibrary","hcl-dependent","terraform-backend","terraform-connection","terraform-data","terraform-locals","terraform-module","terraform-name","terraform-output","terraform-provider","terraform-provisioner","terraform-requiredProviders","terraform-resource","terraform-terraform","terraform-type","terraform-variable"]},"full":true},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"},"fileOperations":{}},"experimental":{"referenceCountCodeLens":false,"refreshModuleProviders":true,"refreshModuleCalls":true,"refreshTerraformVersion":true}},"serverInfo":{"name":"terraform-ls","version":"0.35.0-beta1"}}
```

**Comment by manateelazycat** [comment]
@xinyifly Welcome to provide help, thanks.

**Comment by xinyifly** [comment]
@manateelazycat The params body was actually sent correctly. The result of investigation is that:

terraform-ls has denied the `message_type` field in jsonrpc's request body.

Refer to https://www.jsonrpc.org/specification#notification

`A Notification is a Request object without an "id" member.`

There didn't mention to use `message_type` field to difference message type.

In my test case, simply removing `message_type=*` from `LspServerSender` 's `send_request` , `send_notification` and `send_response` will make terraform-ls run correctly.

Since I don't know the reason to introduce `message_type` initially, it would be better to leave the modification decision for you.

**Comment by manateelazycat** [comment]
@nanasess @xinyifly Can you help to test newest version ? Thanks for help.

**Comment by xinyifly** [comment]
@xinyifly I confirm terraform-ls works correctly in newest version.
