### ISSUE TITLE
为什莫lsp_bridge.py找不到basedpyright.json, 还需要其他的设置？

### ISSUE THREAD

**Issue by e665107** [manateelazycat/lsp-bridge#1027]
Traceback (most recent call last):
  File "/home/e665106/.emacs.d/lisp/lsp-bridge/lsp_bridge.py", line 630, in event_dispatcher
    getattr(self, func_name)(*func_args)
  File "/home/e665106/.emacs.d/lisp/lsp-bridge/lsp_bridge.py", line 884, in _do
    open_file_success = self.open_file(filepath)  # _do is called inside event_loop, so we can block here.
  File "/home/e665106/.emacs.d/lisp/lsp-bridge/lsp_bridge.py", line 708, in open_file
    return self.load_single_lang_server(project_path, filepath)
  File "/home/e665106/.emacs.d/lisp/lsp-bridge/lsp_bridge.py", line 755, in load_single_lang_server
    lang_server_info = load_single_server_info(single_lang_server)
  File "/home/e665106/.emacs.d/lisp/lsp-bridge/lsp_bridge.py", line 1005, in load_single_server_info
    with open(lang_server_info_path, encoding="utf-8", errors="ignore") as f:
FileNotFoundError: [Errno 2] No such file or directory: "/home/e665106/.emacs.d/lisp/lsp-bridge/langserver/Symbol('basedpyright').json"
这个是lsp-bridge报的log

**Comment by manateelazycat** [comment]
需要更新 lsp-bridge 到最新版本， 包括 langserver 下面的  basedpyright.json 文件

e665106 ***@***.***> 于2024年9月2日周一 15:27写道：

**Comment by e665107** [comment]
现在用的就是最新的，在另外一台ubuntu虚拟机上就没问题，不晓得python环境哪里不对，都是3.8.10

**Comment by manateelazycat** [comment]
emacs -Q 试一下， 感觉你的配置把路径多加了一个 Symbol 的字符串

**Comment by e665107** [comment]
不晓得那个symbol如何加上去的，重新装了python3的环境也不行，相同的配置在另外一台上没问题，开始要安装的epc也都装成功了，log所指示的路径下有需要的文件，没找到哪里的问题

**Comment by e665107** [comment]
安装了一个python3.10的环境，目前可以了
