### ISSUE TITLE
使用elixir_ls时错误信息Project directory does not exist

### ISSUE THREAD

**Issue by Akesaka-Hitsuki** [manateelazycat/lsp-bridge#1038]
打开apple.ex文件后直接exited with code 1
创建项目后再用emacs打开的文件，按道理说不存在not exist的问题
换helix使用elixir_ls，能正常运行

emacs version: 29.4

mini config:
```
(add-to-list 'load-path "~/.emacs.d/site-lisp/lsp-bridge")
(add-to-list 'load-path "~/.emacs.d/elpa/yasnippet-20240115.553")
(add-to-list 'load-path "~/.emacs.d/elpa/markdown-mode-20240107.831")
(add-to-list 'load-path "~/.emacs.d/elpa/elixir-mode-20230626.1738")
(require 'elixir-mode)

(require 'yasnippet)
(yas-global-mode 1)

(require 'lsp-bridge)
(setq lsp-bridge-enable-log t)
(setq lsp-bridge-elixir-lsp-server "elixirLS")
(global-lsp-bridge-mode)
```

<details>

<summary>log message</summary>

```
Eval in Emacs: (lsp-bridge--first-start '37189)
Eval in Emacs: (message '"[LSP-Bridge] found language server: /home/akesaka/tools/elixir_ls/language_server.sh")
Start lsp server (elixirLS) for /home/akesaka/code/elixir/apple/lib/apple.ex
Eval in Emacs: (message '"[LSP-Bridge] Active file 'apple.ex', enjoy hacking!")
Handlers: [<class 'core.handler.completion.Completion'>,
 <class 'core.handler.completion_item.CompletionItem'>,
 <class 'core.handler.find_define.FindDefine'>,
 <class 'core.handler.find_type_define.FindTypeDefine'>,
 <class 'core.handler.find_implementation.FindImplementation'>,
 <class 'core.handler.find_references.FindReferences'>,
 <class 'core.handler.peek.PeekFindDefine'>,
 <class 'core.handler.peek.PeekFindReferences'>,
 <class 'core.handler.hover.Hover'>,
 <class 'core.handler.signature_help.SignatureHelp'>,
 <class 'core.handler.prepare_rename.PrepareRename'>,
 <class 'core.handler.rename.Rename'>,
 <class 'core.handler.jdt_uri_resolver.JDTUriResolver'>,
 <class 'core.handler.deno_uri_resolver.DenoUriResolver'>,
 <class 'core.handler.csharp_uri_resolver.CSharpUriResolver'>,
 <class 'core.handler.code_action.CodeAction'>,
 <class 'core.handler.formatting.Formatting'>,
 <class 'core.handler.range_formatting.RangeFormatting'>,
 <class 'core.handler.execute_command.ExecuteCommand'>,
 <class 'core.handler.workspace_symbol.WorkspaceSymbol'>,
 <class 'core.handler.call_hierarchy.PrepareCallHierarchy'>,
 <class 'core.handler.call_hierarchy.CallHierarchy'>,
 <class 'core.handler.call_hierarchy.PrepareCallHierarchyIncomingCalls'>,
 <class 'core.handler.call_hierarchy.PrepareCallHierarchyOutgoingCalls'>,
 <class 'core.handler.call_hierarchy.CallHierarchyIncomingCalls'>,
 <class 'core.handler.call_hierarchy.CallHierarchyOutgoingCalls'>,
 <class 'core.handler.document_symbol.DocumentSymbol'>,
 <class 'core.handler.imenu.IMenu'>,
 <class 'core.handler.jdtls.jdtls_list_overridable_methods.JdtlsListOverridableMethods'>,
 <class 'core.handler.jdtls.jdtls_add_overridable_methods.JdtlsAddOverridableMethods'>,
 <class 'core.handler.inlay_hint.InlayHint'>,
 <class 'core.handler.semantic_tokens.SemanticTokens'>,
 <class 'core.handler.rust_expand_macro.RustExpandMacro'>,
 <class 'core.handler.workspace_diagnostics.WorkspaceDiagnostics'>]
Running /home/akesaka/tools/elixir_ls/launch.sh
Preferred shell is zsh, relaunching
Looking for ASDF install
ASDF install found in /opt/asdf-vm/asdf.sh, sourcing

--- [22:42:35.606339] Send initialize request (24830) to 'elixirLS' for project apple.ex
{
   "id": 24830,
   "method": "initialize",
   "params": {
      "processId": 34393,
      "rootPath": "/home/akesaka/code/elixir/apple/lib/apple.ex",
      "clientInfo": {
         "name": "emacs",
         "version": "lsp-bridge"
      },
      "rootUri": "file:///home/akesaka/code/elixir/apple/lib/apple.ex",
      "capabilities": {
         "workspace": {
            "configuration": true,
            "symbol": {
               "resolveSupport": {
                  "properties": []
               }
            }
         },
         "textDocument": {
            "completion": {
               "completionItem": {
                  "snippetSupport": true,
                  "deprecatedSupport": true,
                  "tagSupport": {
                     "valueSet": [
                        1
                     ]
                  },
                  "resolveSupport": {
                     "properties": [
                        "documentation",
                        "detail",
                        "additionalTextEdits"
                     ]
                  }
               }
            },
            "codeAction": {
               "dynamicRegistration": false,
               "codeActionLiteralSupport": {
                  "codeActionKind": {
                     "valueSet": [
                        "quickfix",
                        "refactor",
                        "refactor.extract",
                        "refactor.inline",
                        "refactor.rewrite",
                        "source",
                        "source.organizeImports"
                     ]
                  }
               },
               "isPreferredSupport": true
            },
            "inlayHint": {
               "dynamicRegistration": false
            },
            "diagnostic": {
               "dynamicRegistration": true,
               "relatedDocumentSupport": true
            },
            "publishDiagnostics": {
               "relatedInformation": true,
               "tagSupport": {
                  "valueSet": [
                     1,
                     2
                  ]
               },
               "versionSupport": true,
               "codeDescriptionSupport": true,
               "dataSupport": true
            }
         },
         "window": {
            "workDoneProgress": true
         }
      },
      "initializationOptions": {}
   },
   "message_type": "request",
   "jsonrpc": "2.0"
}
Eval in Emacs: (lsp-bridge-set-prefix-style '"ascii")
Eval in Emacs: (lsp-bridge-set-server-names '"/home/akesaka/code/elixir/apple/lib/apple.ex" '"" '("elixirLS"))
Installing ElixirLS release v0.23.0
Running in /home/akesaka/code/elixir/apple/lib
Install complete

--- [22:42:37.365011] Recv window/logMessage notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "message": "Started ElixirLS v0.23.0",
      "type": 3
   }
}

--- [22:42:37.365187] Recv window/logMessage notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "message": "Running in /home/akesaka/code/elixir/apple/lib",
      "type": 3
   }
}

--- [22:42:37.368499] Recv window/logMessage notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "message": "ElixirLS built with elixir \"1.17.2\" on OTP \"27\"",
      "type": 3
   }
}

--- [22:42:37.368789] Recv window/logMessage notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "message": "Running on elixir \"1.17.2 (compiled with Erlang/OTP 27)\" on OTP \"27\"",
      "type": 3
   }
}

--- [22:42:37.371153] Recv window/logMessage notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "message": "Protocols are not consolidated",
      "type": 3
   }
}

--- [22:42:37.371872] Recv telemetry/event notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "telemetry/event",
   "params": {
      "name": "eep48",
      "measurements": {},
      "properties": {
         "elixir_ls.eep48": "true",
         "elixir_ls.elixir_release": "1.17",
         "elixir_ls.elixir_version": "1.17.2",
         "elixir_ls.erts_version": "15.0",
         "elixir_ls.mix_env": "dev",
         "elixir_ls.mix_target": "host",
         "elixir_ls.otp_release": "27"
      }
   }
}

--- [22:42:37.372046] Recv window/logMessage notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "message": "Elixir sources not found (checking in /home/runner/work/elixir/elixir). Code navigation to Elixir modules disabled.",
      "type": 3
   }
}

--- [22:42:37.372210] Recv telemetry/event notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "telemetry/event",
   "params": {
      "name": "elixir_sources",
      "measurements": {},
      "properties": {
         "elixir_ls.elixir_release": "1.17",
         "elixir_ls.elixir_sources": "false",
         "elixir_ls.elixir_version": "1.17.2",
         "elixir_ls.erts_version": "15.0",
         "elixir_ls.mix_env": "dev",
         "elixir_ls.mix_target": "host",
         "elixir_ls.otp_release": "27"
      }
   }
}

--- [22:42:37.372558] Recv telemetry/event notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "telemetry/event",
   "params": {
      "name": "otp_sources",
      "measurements": {},
      "properties": {
         "elixir_ls.elixir_release": "1.17",
         "elixir_ls.elixir_version": "1.17.2",
         "elixir_ls.erts_version": "15.0",
         "elixir_ls.mix_env": "dev",
         "elixir_ls.mix_target": "host",
         "elixir_ls.otp_release": "27",
         "elixir_ls.otp_sources": "true"
      }
   }
}

--- [22:42:37.402474] Recv telemetry/event notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "telemetry/event",
   "params": {
      "name": "dialyzer_support",
      "measurements": {},
      "properties": {
         "elixir_ls.dialyzer_support": "true",
         "elixir_ls.dialyzer_support_reason": "",
         "elixir_ls.elixir_release": "1.17",
         "elixir_ls.elixir_version": "1.17.2",
         "elixir_ls.erts_version": "15.0",
         "elixir_ls.mix_env": "dev",
         "elixir_ls.mix_target": "host",
         "elixir_ls.otp_release": "27"
      }
   }
}

--- [22:42:37.407564] Recv response (24830) from 'elixirLS' for project apple.ex
{
   "id": 24830,
   "jsonrpc": "2.0",
   "result": {
      "capabilities": {
         "codeActionProvider": true,
         "codeLensProvider": {
            "resolveProvider": false
         },
         "completionProvider": {
            "triggerCharacters": [
               ".",
               "@",
               "&",
               "%",
               "^",
               ":",
               "!",
               "-",
               "~"
            ]
         },
         "definitionProvider": true,
         "documentFormattingProvider": true,
         "documentOnTypeFormattingProvider": {
            "firstTriggerCharacter": "\n"
         },
         "documentSymbolProvider": {
            "label": "Elixir outline"
         },
         "executeCommandProvider": {
            "commands": [
               "expandMacro:mQDvlrRWUbPgSuYnmp8yAinHisZz5bJp",
               "getExUnitTestsInFile:mQDvlrRWUbPgSuYnmp8yAinHisZz5bJp",
               "manipulatePipes:mQDvlrRWUbPgSuYnmp8yAinHisZz5bJp",
               "mixClean:mQDvlrRWUbPgSuYnmp8yAinHisZz5bJp",
               "restart:mQDvlrRWUbPgSuYnmp8yAinHisZz5bJp",
               "spec:mQDvlrRWUbPgSuYnmp8yAinHisZz5bJp"
            ]
         },
         "foldingRangeProvider": true,
         "hoverProvider": true,
         "implementationProvider": true,
         "macroExpansion": true,
         "referencesProvider": true,
         "selectionRangeProvider": true,
         "signatureHelpProvider": {
            "triggerCharacters": [
               "(",
               ","
            ]
         },
         "textDocumentSync": {
            "change": 2,
            "openClose": true,
            "save": {
               "includeText": true
            }
         },
         "workspace": {
            "workspaceFolders": {
               "changeNotifications": false,
               "supported": false
            }
         },
         "workspaceSymbolProvider": true
      },
      "serverInfo": {
         "name": "ElixirLS",
         "version": "0.23.0"
      }
   }
}

--- [22:42:37.408019] Send initialized notification to 'elixirLS' for project apple.ex

--- [22:42:37.408096] Recv telemetry/event notification from 'elixirLS' for project apple.ex
{
   "method": "initialized",
   "params": {},
   "message_type": "notification",
   "jsonrpc": "2.0"
}
{
   "jsonrpc": "2.0",
   "method": "telemetry/event",
   "params": {
      "name": "lsp_request",
      "measurements": {
         "elixir_ls.lsp_request_time": 23
      },
      "properties": {
         "elixir_ls.elixir_release": "1.17",
         "elixir_ls.elixir_version": "1.17.2",
         "elixir_ls.erts_version": "15.0",
         "elixir_ls.lsp_command": "initialize",
         "elixir_ls.mix_env": "dev",
         "elixir_ls.mix_target": "host",
         "elixir_ls.otp_release": "27"
      }
   }
}

--- [22:42:37.408454] Send workspace/didChangeConfiguration notification to 'elixirLS' for project apple.ex

--- [22:42:37.408592] Recv workspace/configuration request (1) from 'elixirLS' for project apple.ex
{
   "method": "workspace/didChangeConfiguration",
   "params": {
      "settings": {
         "elixirLS": {
            "dialyzerEnabled": true,
            "dialyzerWarnOpts": [],
            "dialyzerFormat": "dialyxir_short",
            "fetchDeps": true,
            "suggestSpecs": true,
            "signatureAfterComplete": true,
            "enableTestLenses": false
         }
      }
   },
   "message_type": "notification",
   "jsonrpc": "2.0"
}
{
   "id": 1,
   "jsonrpc": "2.0",
   "method": "workspace/configuration",
   "params": {
      "items": [
         {
            "scopeUri": "file:///home/akesaka/code/elixir/apple/lib/apple.ex",
            "section": "elixirLS"
         }
      ]
   }
}

--- [22:42:37.408922] Send textDocument/didOpen notification to 'elixirLS' for project apple.ex
{
   "method": "textDocument/didOpen",
   "params": {
      "textDocument": {
         "uri": "file:///home/akesaka/code/elixir/apple/lib/apple.ex",
         "languageId": "elixir",
         "version": 0,
         "text": "defmodule Apple do\n  @moduledoc \"\"\"\n  Documentation for `Apple`.\n  \"\"\"\n\n  @doc \"\"\"\n  Hello world.\n\n  ## Examples\n\n      iex> Apple.hello()\n      :world\n\n  \"\"\"\n  def hello do\n    :world\n  end\nend\n"
      }
   },
   "message_type": "notification",
   "jsonrpc": "2.0"
}

--- [22:42:37.409147] Send response to server request 1 to 'elixirLS' for project apple.ex
{
   "id": 1,
   "result": [
      {
         "dialyzerEnabled": true,
         "dialyzerWarnOpts": [],
         "dialyzerFormat": "dialyxir_short",
         "fetchDeps": true,
         "suggestSpecs": true,
         "signatureAfterComplete": true,
         "enableTestLenses": false
      }
   ],
   "message_type": "response",
   "jsonrpc": "2.0"
}

--- [22:42:37.412592] Recv window/logMessage notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "message": "Received client configuration via workspace/configuration\n%{\"dialyzerEnabled\" => true, \"dialyzerFormat\" => \"dialyxir_short\", \"dialyzerWarnOpts\" => [], \"enableTestLenses\" => false, \"fetchDeps\" => true, \"signatureAfterComplete\" => true, \"suggestSpecs\" => true}",
      "type": 3
   }
}

--- [22:42:37.427944] Recv window/logMessage notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "message": "Project directory /home/akesaka/code/elixir/apple/lib/apple.ex does not exist",
      "type": 1
   }
}

--- [22:42:37.428139] Recv window/showMessage notification from 'elixirLS' for project apple.ex
{
   "jsonrpc": "2.0",
   "method": "window/showMessage",
   "params": {
      "message": "Project directory /home/akesaka/code/elixir/apple/lib/apple.ex does not exist",
      "type": 1
   }
}

--- [22:42:39.435801] LSP server 'elixirLS' exited with code 1
b''
Traceback (most recent call last):
  File "/home/akesaka/.emacs.d/site-lisp/lsp-bridge/core/lspserver.py", line 137, in run
    self.send_message(message)
  File "/home/akesaka/.emacs.d/site-lisp/lsp-bridge/core/lspserver.py", line 90, in send_message
    self.process.stdin.flush()    # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

```
</details>

**Comment by manateelazycat** [comment]
感觉像是对 workspace/configuration 消息的回应不对导致的， 只能周末有时间看一下了。

**Comment by manateelazycat** [comment]
我看了日志， 感觉是 elixirLS 不支持单文件的原因。

elixirLS 把 /home/akesaka/code/elixir/apple/lib/apple.ex 当作目录去看待了。

你看看把这个文件放到一个 git 项目中， 会不会好？

**Comment by Akesaka-Hitsuki** [comment]
这个apple就是mix构建的项目 我在apple这个目录下`git init`后 确实能正常使用了
但是我不太理解的是我用helix的情况下就没有这个问题
```
#helix的language内容
[language-server.elixir_ls]
command = "language_server.sh"

[[language]]
name = "elixir"
scope = "source.elixir"
language-servers = ["elixir_ls"]
```
我不太清楚这其中的差别是什么

**Comment by manateelazycat** [comment]
> 这个apple就是mix构建的项目 我在apple这个目录下`git init`后 确实能正常使用了 但是我不太理解的是我用helix的情况下就没有这个问题
> 
> ```
> #helix的language.toml内容
> [language-server.elixir_ls]
> command = "language_server.sh"
> 
> [[language]]
> name = "elixir"
> scope = "source.elixir"
> language-servers = ["elixir_ls"]
> ```
> 
> 我不太清楚这其中的差别是什么

应该是 Helix 根据某些项目特征把项目 root 的路径传给 lsp server 了。

有两种解决方案：
1. 修改 lsp-bridge-get-project-path-by-filepath， 这样不用 git init 也可以

https://github.com/manateelazycat/lazycat-emacs/blob/7f9d0a2f1b8ebca467ad0ceea7a8bd38d38c8f10/site-lisp/config/init-lsp-bridge.el#L122

2. 看看项目下有啥特征的文件， 可以告诉我， 我来给 lsp-bridge--get-project-path-func 加规则

**Comment by manateelazycat** [comment]
我已经加入补丁 https://github.com/manateelazycat/lsp-bridge/commit/0411c2402b4ff0af05cda9740c387c8576c4a5e3

告知用户 elixirLS lsp server 不支持单文件补全。

**Comment by Akesaka-Hitsuki** [comment]
```
tree myproject
myproject
├── lib
│   └── myproject.ex
├── mix.exs
├── README.md
└── test
    ├── myproject_test.exs
    └── test_helper.exs
```
`mix.exs`是elixir项目的配置文件，就用它吧

**Comment by manateelazycat** [comment]
@Akesaka-Hitsuki 

我推送一个补丁 https://github.com/manateelazycat/lsp-bridge/commit/665110e14bb71f12eda6cbcee69cc4b71821624a

测试一下吧，谢谢！

**Comment by Akesaka-Hitsuki** [comment]
尝试用mini config测试 报错
```
Eval in Emacs: (lsp-bridge--first-start '50843)
Traceback (most recent call last):
  File "/home/akesaka/.emacs.d/site-lisp/lsp-bridge/lsp_bridge.py", line 630, in event_dispatcher
    getattr(self, func_name)(*func_args)
  File "/home/akesaka/.emacs.d/site-lisp/lsp-bridge/lsp_bridge.py", line 916, in _do
    open_file_success = self.open_file(filepath)  # _do is called inside event_loop, so we can block here.
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akesaka/.emacs.d/site-lisp/lsp-bridge/lsp_bridge.py", line 717, in open_file
    return self.load_single_lang_server(project_path, filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akesaka/.emacs.d/site-lisp/lsp-bridge/lsp_bridge.py", line 764, in load_single_lang_server
    project_root = self.find_project_root(filepath, lang_server_info["project-files"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akesaka/.emacs.d/site-lisp/lsp-bridge/lsp_bridge.py", line 789, in find_project_root
    current_dir = os.path.abspath(filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 410, in abspath
TypeError: expected str, bytes or os.PathLike object, not LspBridge
```

**Comment by manateelazycat** [comment]
@Akesaka-Hitsuki 忘记 self 参数了， https://github.com/manateelazycat/lsp-bridge/commit/26b217899b38016f3501e5a3b6ab85b20cda2b3b

再麻烦试一下， 谢谢

**Comment by Akesaka-Hitsuki** [comment]
mini config测试了一下 正常了👍

**Comment by manateelazycat** [comment]
好的， 感谢反馈。

lsp-bridge 以前主要是依靠 git 或者 .dir-local 来定位工程目录的， 今天和您的交流中想到了可以根据不同语言提供的 project-files 来辅助定位 project root, 这样的开箱即用的体验会更加好一点。
