### ISSUE TITLE
lsp-bridge使用nil做为nix的lsp-server时报错

### ISSUE THREAD

**Issue by chap9** [manateelazycat/lsp-bridge#1043]
相关配置：
```
(straight-use-package
  '
  (lsp-bridge
    :type git
    :host github
    :repo "manateelazycat/lsp-bridge"
    :files
    (:defaults
      "*.el"
      "*.py"
      "acm"
      "core"
      "langserver"
      "multiserver"
      "resources")
    :build (:not compile))
  )

(require 'lsp-bridge)

(setq lsp-bridge-nix-lsp-server "nil")

(use-package nix-mode
  :straight t
  :hook (nix-mode . lsp-bridge-mode)
  :ensure t)

```

```
--- [14:46:54.661453] Send textDocument/didSave notification to 'nil' for project 
2024-09-20T06:46:54.661903Z ERROR nil: Unexpected error: Unhandled notification: textDocument/didSave

--- [14:46:54.662853] LSP server 'nil' exited with code 101
b''
Traceback (most recent call last):
  File "/Users/dingoding/work/emacs.d/straight/repos/lsp-bridge/core/lspserver.py", line 137, in run
    self.send_message(message)
  File "/Users/dingoding/work/emacs.d/straight/repos/lsp-bridge/core/lspserver.py", line 90, in send_message
    self.process.stdin.flush()    # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by manateelazycat** [comment]
你安装了 https://github.com/oxalica/nil 吗？

**Comment by chap9** [comment]
确认装了，nil最开始是能正常启动的，但一旦保存文档，就会报错。nixd测试了下可以正常用。

**Comment by manateelazycat** [comment]
lsp-bridge-enable-log 设置为 t, 给一下 `*lsp-bridge*` 的完整日志吧。

**Comment by chap9** [comment]
init.el配置：

```
;;; -*- lexical-binding: t -*-

(use-package bind-key :demand t :ensure t)
(use-package diminish :demand t :ensure t)
(use-package nix-mode :demand t :ensure t)


(add-to-list 'load-path "/Users/dingoding/work/emacs.d.2/markdown-mode")
(require 'markdown-mode)

(add-to-list 'load-path "/Users/dingoding/work/emacs.d.2/yasnippet")
(require 'yasnippet)

(yas-global-mode 1)

(add-to-list 'load-path "/Users/dingoding/work/lsp-bridge")
(require 'lsp-bridge)

(setq lsp-bridge-enable-log t)
(global-lsp-bridge-mode)

(setq lsp-bridge-nix-lsp-server "nil")

```

完整log：

```
Eval in Emacs: (lsp-bridge--first-start '50618)
Eval in Emacs: (message '"[LSP-Bridge] found language server: /Users/chap9/.nix-profile/bin/nil")
Start lsp server (nil) for /Users/chap9/work/emacs.d.2/test.nix
Eval in Emacs: (message '"[LSP-Bridge] Active file 'test.nix', enjoy hacking!")
Handlers: [<class 'core.handler.completion.Completion'>,
 <class 'core.handler.completion_item.CompletionItem'>,
 <class 'core.handler.find_define.FindDefine'>,
 <class 'core.handler.find_type_define.FindTypeDefine'>,
 <class 'core.handler.find_implementation.FindImplementation'>,
 <class 'core.handler.find_references.FindReferences'>,
 <class 'core.handler.peek.PeekFindDefine'>,
 <class 'core.handler.peek.PeekFindReferences'>,
 <class 'core.handler.hover.Hover'>,
 <class 'core.handler.signature_help.SignatureHelp'>,
 <class 'core.handler.prepare_rename.PrepareRename'>,
 <class 'core.handler.rename.Rename'>,
 <class 'core.handler.jdt_uri_resolver.JDTUriResolver'>,
 <class 'core.handler.deno_uri_resolver.DenoUriResolver'>,
 <class 'core.handler.csharp_uri_resolver.CSharpUriResolver'>,
 <class 'core.handler.code_action.CodeAction'>,
 <class 'core.handler.formatting.Formatting'>,
 <class 'core.handler.range_formatting.RangeFormatting'>,
 <class 'core.handler.execute_command.ExecuteCommand'>,
 <class 'core.handler.workspace_symbol.WorkspaceSymbol'>,
 <class 'core.handler.call_hierarchy.PrepareCallHierarchy'>,
 <class 'core.handler.call_hierarchy.CallHierarchy'>,
 <class 'core.handler.call_hierarchy.PrepareCallHierarchyIncomingCalls'>,
 <class 'core.handler.call_hierarchy.PrepareCallHierarchyOutgoingCalls'>,
 <class 'core.handler.call_hierarchy.CallHierarchyIncomingCalls'>,
 <class 'core.handler.call_hierarchy.CallHierarchyOutgoingCalls'>,
 <class 'core.handler.document_symbol.DocumentSymbol'>,
 <class 'core.handler.imenu.IMenu'>,
 <class 'core.handler.jdtls.jdtls_list_overridable_methods.JdtlsListOverridableMethods'>,
 <class 'core.handler.jdtls.jdtls_add_overridable_methods.JdtlsAddOverridableMethods'>,
 <class 'core.handler.inlay_hint.InlayHint'>,
 <class 'core.handler.semantic_tokens.SemanticTokens'>,
 <class 'core.handler.rust_expand_macro.RustExpandMacro'>,
 <class 'core.handler.workspace_diagnostics.WorkspaceDiagnostics'>]

--- [12:15:11.298885] Send initialize request (43600) to 'nil' for project test.nix
{
   "id": 43600,
   "method": "initialize",
   "params": {
      "processId": 52374,
      "rootPath": "/Users/chap9/work/emacs.d.2/test.nix",
      "clientInfo": {
         "name": "emacs",
         "version": "lsp-bridge"
      },
      "rootUri": "file:///Users/chap9/work/emacs.d.2/test.nix",
      "capabilities": {
         "workspace": {
            "configuration": true,
            "symbol": {
               "resolveSupport": {
                  "properties": []
               }
            }
         },
         "textDocument": {
            "completion": {
               "completionItem": {
                  "snippetSupport": true,
                  "deprecatedSupport": true,
                  "tagSupport": {
                     "valueSet": [
                        1
                     ]
                  },
                  "resolveSupport": {
                     "properties": [
                        "documentation",
                        "detail",
                        "additionalTextEdits"
                     ]
                  }
               }
            },
            "codeAction": {
               "dynamicRegistration": false,
               "codeActionLiteralSupport": {
                  "codeActionKind": {
                     "valueSet": [
                        "quickfix",
                        "refactor",
                        "refactor.extract",
                        "refactor.inline",
                        "refactor.rewrite",
                        "source",
                        "source.organizeImports"
                     ]
                  }
               },
               "isPreferredSupport": true
            },
            "inlayHint": {
               "dynamicRegistration": false
            },
            "diagnostic": {
               "dynamicRegistration": true,
               "relatedDocumentSupport": true
            },
            "publishDiagnostics": {
               "relatedInformation": true,
               "tagSupport": {
                  "valueSet": [
                     1,
                     2
                  ]
               },
               "versionSupport": true,
               "codeDescriptionSupport": true,
               "dataSupport": true
            }
         },
         "window": {
            "workDoneProgress": true
         }
      },
      "initializationOptions": {}
   },
   "message_type": "request",
   "jsonrpc": "2.0"
}

--- [12:15:11.299272] Recv response (43600) from 'nil' for project test.nix
Eval in Emacs: (lsp-bridge-set-prefix-style '"ascii")
{
   "jsonrpc": "2.0",
   "id": 43600,
   "result": {
      "capabilities": {
         "codeActionProvider": true,
         "completionProvider": {
            "triggerCharacters": [
               ".",
               "?"
            ]
         },
         "definitionProvider": true,
         "documentFormattingProvider": true,
         "documentHighlightProvider": true,
         "documentLinkProvider": {
            "resolveProvider": true
         },
         "documentSymbolProvider": true,
         "hoverProvider": true,
         "referencesProvider": true,
         "renameProvider": {
            "prepareProvider": true
         },
         "selectionRangeProvider": true,
         "semanticTokensProvider": {
            "full": {
               "delta": false
            },
            "legend": {
               "tokenModifiers": [
                  "builtin",
                  "conditional",
                  "definition",
                  "delimiter",
                  "escape",
                  "parenthesis",
                  "readonly",
                  "unresolved",
                  "withAttribute"
               ],
               "tokenTypes": [
                  "boolean",
                  "comment",
                  "constant",
                  "function",
                  "keyword",
                  "number",
                  "operator",
                  "parameter",
                  "path",
                  "property",
                  "punctuation",
                  "string",
                  "struct",
                  "variable"
               ]
            },
            "range": true
         },
         "textDocumentSync": {
            "change": 2,
            "openClose": true
         }
      },
      "serverInfo": {
         "name": "nil",
         "version": "2024-08-06"
      }
   }
}

--- [12:15:11.356660] Send initialized notification to 'nil' for project test.nix
Eval in Emacs: (lsp-bridge-set-server-names '"/Users/chap9/work/emacs.d.2/test.nix" '"" '("nil"))

--- [12:15:11.456045] Recv workspace/configuration request (0) from 'nil' for project test.nix
{
   "method": "initialized",
   "params": {},
   "message_type": "notification",
   "jsonrpc": "2.0"
}
{
   "jsonrpc": "2.0",
   "id": 0,
   "method": "workspace/configuration",
   "params": {
      "items": [
         {
            "section": "nil"
         }
      ]
   }
}

--- [12:15:11.456399] Send workspace/didChangeConfiguration notification to 'nil' for project test.nix

--- [12:15:11.456513] Recv workspace/configuration request (1) from 'nil' for project test.nix
{
   "method": "workspace/didChangeConfiguration",
   "params": {
      "settings": {}
   },
   "message_type": "notification",
   "jsonrpc": "2.0"
}
{
   "jsonrpc": "2.0",
   "id": 1,
   "method": "workspace/configuration",
   "params": {
      "items": [
         {
            "section": "nil"
         }
      ]
   }
}

--- [12:15:11.459944] Send textDocument/didOpen notification to 'nil' for project test.nix
{
   "method": "textDocument/didOpen",
   "params": {
      "textDocument": {
         "uri": "file:///Users/chap9/work/emacs.d.2/test.nix",
         "languageId": "nix",
         "version": 0,
         "text": "{ pkgs, lib, ... }:\n\n{\n  # \u516c\u5171\u57fa\u7840\u5305\n  home.packages = with pkgs; [\n    direnv\n    vim\n  ];\n\n  programs.home-manager.enable = true;\n\n  home.stateVersion = \"24.05\";\n}\n"
      }
   },
   "message_type": "notification",
   "jsonrpc": "2.0"
}

--- [12:15:11.464907] Recv textDocument/publishDiagnostics notification from 'nil' for project test.nix

--- [12:15:11.512870] Send response to server request 0 to 'nil' for project test.nix

--- [12:15:11.513023] Record diagnostics from 'nil' for file test.nix
{
   "id": 0,
   "result": [
      null
   ],
   "message_type": "response",
   "jsonrpc": "2.0"
}
{
   "jsonrpc": "2.0",
   "method": "textDocument/publishDiagnostics",
   "params": {
      "diagnostics": [
         {
            "code": "unused_binding",
            "message": "Unused binding",
            "range": {
               "end": {
                  "character": 11,
                  "line": 0
               },
               "start": {
                  "character": 8,
                  "line": 0
               }
            },
            "relatedInformation": [],
            "severity": 2,
            "tags": [
               1
            ]
         }
      ],
      "uri": "file:///Users/chap9/work/emacs.d.2/test.nix"
   }
}

--- [12:15:11.513233] Send response to server request 1 to 'nil' for project test.nix
{
   "id": 1,
   "result": [
      null
   ],
   "message_type": "response",
   "jsonrpc": "2.0"
}
Eval in Emacs: (lsp-bridge-diagnostic--render '"/Users/chap9/work/emacs.d.2/test.nix" '"" '((:code "unused_binding" :message "Unused binding" :range (:end (:character 11 :line 0) :start (:character 8 :line 0)) :relatedInformation () :severity 2 :tags (1) :server-name "nil")) '1)

--- [12:15:14.744090] Send textDocument/didChange notification to 'nil' for project test.nix
{
   "method": "textDocument/didChange",
   "params": {
      "textDocument": {
         "uri": "file:///Users/chap9/work/emacs.d.2/test.nix",
         "version": 1
      },
      "contentChanges": [
         {
            "range": {
               "start": {
                  "line": 0,
                  "character": 1
               },
               "end": {
                  "line": 0,
                  "character": 2
               }
            },
            "rangeLength": 1,
            "text": ""
         }
      ]
   },
   "message_type": "notification",
   "jsonrpc": "2.0"
}
Eval in Emacs: (lsp-bridge-search-backend--record-items '"search-file-words" '())

--- [12:15:14.746010] Recv textDocument/publishDiagnostics notification from 'nil' for project test.nix

--- [12:15:14.746092] Record diagnostics from 'nil' for file test.nix
{
   "jsonrpc": "2.0",
   "method": "textDocument/publishDiagnostics",
   "params": {
      "diagnostics": [
         {
            "code": "unused_binding",
            "message": "Unused binding",
            "range": {
               "end": {
                  "character": 10,
                  "line": 0
               },
               "start": {
                  "character": 7,
                  "line": 0
               }
            },
            "relatedInformation": [],
            "severity": 2,
            "tags": [
               1
            ]
         }
      ],
      "uri": "file:///Users/chap9/work/emacs.d.2/test.nix"
   }
}

--- [12:15:14.869057] Send textDocument/completion request (61666) to 'nil' for project test.nix
{
   "id": 61666,
   "method": "textDocument/completion",
   "params": {
      "position": {
         "line": 0,
         "character": 1
      },
      "context": {
         "triggerKind": 1
      },
      "textDocument": {
         "uri": "file:///Users/chap9/work/emacs.d.2/test.nix"
      }
   },
   "message_type": "request",
   "jsonrpc": "2.0"
}

--- [12:15:14.870719] Recv textDocument/completion response (61666) from 'nil' for project test.nix

--- [12:15:14.870915] Got completion candidates (1) from 'nil' for file test.nix

--- [12:15:14.870984] Record completion candidates (1) from 'nil' for file test.nix
Eval in Emacs: (lsp-bridge-completion--record-items '"/Users/chap9/work/emacs.d.2/test.nix" '"" '((:key "pkgs_{ }_" :icon "variable" :label "pkgs" :displayLabel "pkgs => { }" :deprecated () :insertText () :insertTextFormat 1 :textEdit (:newText "pkgs" :range (:end (:character 1 :line 0) :start (:character 1 :line 0))) :score 1000 :sortText "" :server "nil" :backend "lsp" :additionalTextEdits ())) '(:line 0 :character 1) '"nil" '("." "?") '("nil"))
{
   "jsonrpc": "2.0",
   "id": 61666,
   "result": [
      {
         "detail": "{ }",
         "insertTextFormat": 1,
         "insertTextMode": 2,
         "kind": 6,
         "label": "config",
         "labelDetails": {
            "detail": ": {\u2026}"
         },
         "textEdit": {
            "newText": "config",
            "range": {
               "end": {
                  "character": 1,
                  "line": 0
               },
               "start": {
                  "character": 1,
                  "line": 0
               }
            }
         }
      },
      {
         "detail": "{ }",
         "insertTextFormat": 1,
         "insertTextMode": 2,
         "kind": 6,
         "label": "lib",
         "labelDetails": {
            "detail": ": {\u2026}"
         },
         "textEdit": {
            "newText": "lib",
            "range": {
               "end": {
                  "character": 1,
                  "line": 0
               },
               "start": {
                  "character": 1,
                  "line": 0
               }
            }
         }
      },
      {
         "detail": "{ }",
         "insertTextFormat": 1,
         "insertTextMode": 2,
         "kind": 6,
         "label": "pkgs",
         "labelDetails": {
            "detail": ": {\u2026}"
         },
         "textEdit": {
            "newText": "pkgs",
            "range": {
               "end": {
                  "character": 1,
                  "line": 0
               },
               "start": {
                  "character": 1,
                  "line": 0
               }
            }
         }
      }
   ]
}

--- [12:15:15.034132] Send textDocument/didChange notification to 'nil' for project test.nix
{
   "method": "textDocument/didChange",
   "params": {
      "textDocument": {
         "uri": "file:///Users/chap9/work/emacs.d.2/test.nix",
         "version": 2
      },
      "contentChanges": [
         {
            "range": {
               "start": {
                  "line": 0,
                  "character": 1
               },
               "end": {
                  "line": 0,
                  "character": 1
               }
            },
            "rangeLength": 0,
            "text": " "
         }
      ]
   },
   "message_type": "notification",
   "jsonrpc": "2.0"
}
Eval in Emacs: (lsp-bridge-search-backend--record-items '"search-file-words" '())

--- [12:15:15.035106] Recv textDocument/publishDiagnostics notification from 'nil' for project test.nix

--- [12:15:15.035173] Record diagnostics from 'nil' for file test.nix
{
   "jsonrpc": "2.0",
   "method": "textDocument/publishDiagnostics",
   "params": {
      "diagnostics": [
         {
            "code": "unused_binding",
            "message": "Unused binding",
            "range": {
               "end": {
                  "character": 11,
                  "line": 0
               },
               "start": {
                  "character": 8,
                  "line": 0
               }
            },
            "relatedInformation": [],
            "severity": 2,
            "tags": [
               1
            ]
         }
      ],
      "uri": "file:///Users/chap9/work/emacs.d.2/test.nix"
   }
}

--- [12:15:15.139711] Send textDocument/completion request (12132) to 'nil' for project test.nix
{
   "id": 12132,
   "method": "textDocument/completion",
   "params": {
      "position": {
         "line": 0,
         "character": 2
      },
      "context": {
         "triggerKind": 1
      },
      "textDocument": {
         "uri": "file:///Users/chap9/work/emacs.d.2/test.nix"
      }
   },
   "message_type": "request",
   "jsonrpc": "2.0"
}

--- [12:15:15.140765] Recv textDocument/completion response (12132) from 'nil' for project test.nix

--- [12:15:15.140987] Got completion candidates (1) from 'nil' for file test.nix

--- [12:15:15.141087] Record completion candidates (1) from 'nil' for file test.nix
Eval in Emacs: (lsp-bridge-completion--record-items '"/Users/chap9/work/emacs.d.2/test.nix" '"" '((:key "pkgs_{ }_" :icon "variable" :label "pkgs" :displayLabel "pkgs => { }" :deprecated () :insertText () :insertTextFormat 1 :textEdit (:newText "pkgs" :range (:end (:character 2 :line 0) :start (:character 2 :line 0))) :score 1000 :sortText "" :server "nil" :backend "lsp" :additionalTextEdits ())) '(:line 0 :character 2) '"nil" '("." "?") '("nil"))
{
   "jsonrpc": "2.0",
   "id": 12132,
   "result": [
      {
         "detail": "{ }",
         "insertTextFormat": 1,
         "insertTextMode": 2,
         "kind": 6,
         "label": "config",
         "labelDetails": {
            "detail": ": {\u2026}"
         },
         "textEdit": {
            "newText": "config",
            "range": {
               "end": {
                  "character": 2,
                  "line": 0
               },
               "start": {
                  "character": 2,
                  "line": 0
               }
            }
         }
      },
      {
         "detail": "{ }",
         "insertTextFormat": 1,
         "insertTextMode": 2,
         "kind": 6,
         "label": "lib",
         "labelDetails": {
            "detail": ": {\u2026}"
         },
         "textEdit": {
            "newText": "lib",
            "range": {
               "end": {
                  "character": 2,
                  "line": 0
               },
               "start": {
                  "character": 2,
                  "line": 0
               }
            }
         }
      },
      {
         "detail": "{ }",
         "insertTextFormat": 1,
         "insertTextMode": 2,
         "kind": 6,
         "label": "pkgs",
         "labelDetails": {
            "detail": ": {\u2026}"
         },
         "textEdit": {
            "newText": "pkgs",
            "range": {
               "end": {
                  "character": 2,
                  "line": 0
               },
               "start": {
                  "character": 2,
                  "line": 0
               }
            }
         }
      }
   ]
}
Eval in Emacs: (lsp-bridge-diagnostic--render '"/Users/chap9/work/emacs.d.2/test.nix" '"" '((:code "unused_binding" :message "Unused binding" :range (:end (:character 11 :line 0) :start (:character 8 :line 0)) :relatedInformation () :severity 2 :tags (1) :server-name "nil")) '1)

--- [12:15:15.875875] Send textDocument/didSave notification to 'nil' for project test.nix
{
   "method": "textDocument/didSave",
   "params": {
      "textDocument": {
         "uri": "file:///Users/chap9/work/emacs.d.2/test.nix"
      }
   },
   "message_type": "notification",
   "jsonrpc": "2.0"
}
2024-09-23T04:15:15.876045Z ERROR nil: Unexpected error: Unhandled notification: textDocument/didSave

--- [12:15:15.876539] LSP server 'nil' exited with code 101
b''

*** lsp-bridge-try-completion execute predicate 'lsp-bridge--not-delete-command' failed with result: 'nil'

*** lsp-bridge-try-completion execute predicate 'lsp-bridge--not-delete-command' failed with result: 'nil'

*** lsp-bridge-try-completion execute predicate 'lsp-bridge--not-only-blank-before-cursor' failed with result: 'nil'

*** lsp-bridge-try-completion execute predicate 'lsp-bridge--not-only-blank-before-cursor' failed with result: 'nil'

*** lsp-bridge-try-completion execute predicate 'lsp-bridge--not-only-blank-before-cursor' failed with result: 'nil'

```

触发条件：

按 ctrl-x ctrl-s 保存文件时触发

**Comment by manateelazycat** [comment]
这个太奇怪了， 给 LSP Server 发送 didSave 这个提示 LSP server 就挂了， 这是最标准的协议呀。

**Comment by manateelazycat** [comment]
可以尝试报错给 nil lsp server 的作者， 看看他怎么判断？

**Comment by xinyifly** [comment]
@manateelazycat 对比了一下 lsp-bridge 和 lsp-mode 的日志，发现 lsp-mode 与 nil 通信时根本没有发送 `textDocument/didSave`

对比 nil 与 typescript-language-server 的 Capabilities 发现

nil

```
|-[-] textDocumentSync:
|  |-[X] openClose: t
|  `-[X] change: 2
```

typescript-language-server

```
|-[X] textDocumentSync: 2
```

查阅文档发现 TextDocumentSyncOptions 的定义有两处：

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentSyncOptions

```
export interface [TextDocumentSyncOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentSyncOptions) {
	/**
	 * Open and close notifications are sent to the server. If omitted open
	 * close notifications should not be sent.
	 */
	openClose?: boolean;

	/**
	 * Change notifications are sent to the server. See
	 * TextDocumentSyncKind.None, TextDocumentSyncKind.Full and
	 * TextDocumentSyncKind.Incremental. If omitted it defaults to
	 * TextDocumentSyncKind.None.
	 */
	change?: [TextDocumentSyncKind](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentSyncKind);
}
```

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didRename

```
export interface [TextDocumentSyncOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentSyncOptions) {
	/**
	 * Open and close notifications are sent to the server. If omitted open
	 * close notification should not be sent.
	 */
	openClose?: boolean;
	/**
	 * Change notifications are sent to the server. See
	 * TextDocumentSyncKind.None, TextDocumentSyncKind.Full and
	 * TextDocumentSyncKind.Incremental. If omitted it defaults to
	 * TextDocumentSyncKind.None.
	 */
	change?: [TextDocumentSyncKind](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentSyncKind);
	/**
	 * If present will save notifications are sent to the server. If omitted
	 * the notification should not be sent.
	 */
	willSave?: boolean;
	/**
	 * If present will save wait until requests are sent to the server. If
	 * omitted the request should not be sent.
	 */
	willSaveWaitUntil?: boolean;
	/**
	 * If present save notifications are sent to the server. If omitted the
	 * notification should not be sent.
	 */
	save?: boolean | [SaveOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#saveOptions);
}
```

其中后面那一处看起来不太正式但更完整，这应该就是 lsp-mode 不向 nil 发送 `textDocument/didSave` 的原因

**Comment by manateelazycat** [comment]
好的， 感谢大佬提供线索， 我一会看看

**Comment by manateelazycat** [comment]
Has fixed by https://github.com/manateelazycat/lsp-bridge/commit/6f08095cfce1f766d91b1644744a14d4c2058667

Thanks @xinyifly  for hint!
