### ISSUE TITLE
MacOS 最新版更新后，lsp server 起不来了。

### ISSUE THREAD

**Issue by smallzhan** [manateelazycat/lsp-bridge#106]
Emacs 28.1, MacOS 12.3.1, 打开 Python 文件，报下面的错。
commit 132d5d96cfd9c3dbd61068215da52cc70c35e8d2
之前老版本是可以的。
好像是从 commit 53997b9db4380fbc1d658ff35f9c26ece549e92e  这个开始出问题的。上面一个版本还行。

```Exception in thread Thread-2 (event_dispatcher):
Traceback (most recent call last):
  File "/Users/guoqiang/.asdf/installs/python/3.10.4/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Users/guoqiang/.asdf/installs/python/3.10.4/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/guoqiang/.emacs.d/site-lisp/lsp-bridge/lsp-bridge.py", line 104, in event_dispatcher
    getattr(self, func_name)(*func_args)
  File "/Users/guoqiang/.emacs.d/site-lisp/lsp-bridge/lsp-bridge.py", line 190, in _do
    self._open_file(filepath)  # _do is called inside event_loop, so we can block here.
  File "/Users/guoqiang/.emacs.d/site-lisp/lsp-bridge/lsp-bridge.py", line 140, in _open_file
    lang_server_info: dict = load_lang_server_info(lang_server)
  File "/Users/guoqiang/.emacs.d/site-lisp/lsp-bridge/lsp-bridge.py", line 256, in load_lang_server_info
    if os.path.exists(lang_server) and os.path.sep in lang_server:
  File "/Users/guoqiang/.asdf/installs/python/3.10.4/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
```

**Comment by manateelazycat** [comment]
在 256 行插入一条语句 ```print("********** '{}' '{}'".format(lang_server, type(lang_server)))``` 然后重新尝试一下， 把******开头的日志返回给我看一下。

**Comment by manateelazycat** [comment]
更新看一下

**Comment by smallzhan** [comment]
更新没解决，输出是

********** '[]' '<class 'list'>'

**Comment by manateelazycat** [comment]
> 更新没解决，输出是
> 
> ********** '[]' '<class 'list'>'

加我微信吧， 我发你邮箱了，这样好沟通一点。

**Comment by imkunzo** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/2231907/169039849-34e893b7-c996-4a17-95a7-f613b9c25924.png">
我在这里打印了 result，emacs 里报错内容如下：
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/2231907/169040129-76131a55-63e2-4281-9261-2d061bf2597a.png">

**Comment by manateelazycat** [comment]
代码回滚了，这个错误已经消失了。

**Comment by imkunzo** [comment]
> 代码回滚了，这个错误已经消失了。

@smallzhan 不知道你那恢复没有，我这回滚后仍然会报同样的错误。

**Comment by smallzhan** [comment]
> > 代码回滚了，这个错误已经消失了。
> 
> @smallzhan 不知道你那恢复没有，我这回滚后仍然会报同样的错误。

刚忙完其他事，我这验证了下，已经好了。
