### ISSUE TITLE
查找引用时报：TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by lkzz** [manateelazycat/lsp-bridge#107]
--- Recv response (13451): textDocument/references
Error when processing response 13451
Traceback (most recent call last):
  File "/Users/xxx/.config/emacs/cache/straight/repos/lsp-bridge/core/handler/__init__.py", line 63, in handle_response
    self.process_response(response)
  File "/Users/xxx/.config/emacs/cache/straight/repos/lsp-bridge/core/handler/find_references.py", line 22, in process_response
    for uri_info in response:
TypeError: 'NoneType' object is not iterable

<img width="811" alt="image" src="https://user-images.githubusercontent.com/5388526/169023575-df11c90c-a823-4ff1-be2d-871eb5332515.png">

在go项目中查找一个未被引用的方法时会报以上错误，看着是要判断一下response？

**Comment by manateelazycat** [comment]
更新测试一下？

**Comment by lkzz** [comment]
修复了，感谢！
