### ISSUE TITLE
Didn't work well on haskell

### ISSUE THREAD

**Issue by SoulAttacker** [manateelazycat/lsp-bridge#1121]
## Bug show
`LSP` didn't work, only the tabnie work well. `lsp-bridge-find-def` and other lsp-related funcs didn't work well. but lsp-bridge works well on other projects in other languages like cpp, python, ocaml ...

## Environment
OS: macOS Ventura 13.3.1 arm64
Emacs version: 29.4 (built by emacs-plus)
haskell-language-server-wrapper version: 2.9.0.1 (GHC: 9.10.1)
python: 3.9.12 (with all requirements)
stack version: Version 3.1.1, Git revision d8cef4ea052430ea09ce7836c41e68b52d04fd73 aarch64 hpack-0.37.0

## Minimal emacs setup
```emacs-lisp
;; load-path
(let ((default-directory  user-emacs-directory))
  (add-to-list 'load-path (expand-file-name "package" default-directory))
  (normal-top-level-add-subdirs-to-load-path))

;; setting for haskell mode refer to [https://github.com/haskell/haskell-mode]
(require 'haskell)
(add-to-list 'auto-mode-alist '("\\.hs\\'" . haskell-mode))
(add-to-list 'auto-mode-alist '("\\.lhs\\'" . haskell-mode))


(require 'lsp-bridge)
(setq
 lsp-bridge-python-command    "~/miniconda3/bin/python"

 lsp-bridge-enable-log t
 lsp-bridge-python-lsp-server 'pylsp
 lsp-bridge-c-lsp-server      'clangd

 lsp-bridge-enable-diagnostics t
 lsp-bridge-enable-hover-diagnostic t
 lsp-bridge-enable-org-babel        t
 lsp-bridge-enable-completion-in-string t
 lsp-bridge-enable-signature-help t
 lsp-bridge-enable-completion-in-minibuffer t
 lsp-bridge-enable-inlay-hint t

 ; acm-candidate-match-function 'orderless-regexp
 acm-enable-doc t
 acm-enable-icon t
 acm-enable-doc-markdown-render t
 acm-enable-tabnie nil
 acm-enable-search-file-words t
 acm-enable-yas t
 acm-backend-lsp-enable-auto-import t
 acm-enable-preview nil)

(add-hook 'prog-mode-hook 'lsp-bridge-mode)
```

## Haskell project
Just a template generated from
```bash
stack new lox
```
I tested both adding the `hie.yaml` or not, both of them didn't work well. Also, it's initialized by `git init .`.

## lsp-bridge log (full log please see the additional file)
**HIGHLIGHT**:
```bash
--- [02:30:06.132980] Recv $/progress notification from 'hls' for project lox
Traceback (most recent call last):
  File "/Users/soulwalker/.config/emacs/package/lsp-bridge/core/lspserver.py", line 360, in lsp_message_dispatcher
    self.handle_recv_message(message["content"])
  File "/Users/soulwalker/.config/emacs/package/lsp-bridge/core/lspserver.py", line 891, in handle_recv_message
    self.handle_work_done_progress_message(message)
  File "/Users/soulwalker/.config/emacs/package/lsp-bridge/core/lspserver.py", line 856, in handle_work_done_progress_message
    progress_message += token_attr
TypeError: can only concatenate str (not "int") to str
```

## Full log
[lsp-bridge.log](https://github.com/user-attachments/files/18012842/lsp-bridge.log)

## Finally
I like your project, thank you for your contribution. Have a nice day :)

**Comment by manateelazycat** [comment]
Has fixed in newest version, thanks for report.

Please re-open it if still have problem.
