### ISSUE TITLE
typescript server在mac下面报错

### ISSUE THREAD

**Issue by zilongshanren** [manateelazycat/lsp-bridge#150]
```
"message": "Request textDocument/completion failed with message: Error processing request. Debug Failure. False 

expression.\nError: Debug Failure. False expression.\n    at checkChangeRange 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:37870:26)\n    at Object.updateSourceFile 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:37460:13)\n    at Object.updateSourceFile 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:30497:47)\n    at Object.updateLanguageServiceSourceFile 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:161435:40)\n    at acquireOrUpdateDocument 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:133120:43)\n    at Object.updateDocumentWithKey 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:133062:20)\n    at Object.getOrCreateSourceFileByPath [as 

getSourceFileByPath] (/usr/local/lib/node_modules/typescript/lib/tsserver.js:161795:53)\n    at 

tryReuseStructureFromOldProgram (/usr/local/lib/node_modules/typescript/lib/tsserver.js:115146:28)\n    at 

Object.createProgram (/usr/local/lib/node_modules/typescript/lib/tsserver.js:114658:29)\n    at synchronizeHostData 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:161682:26)\n    at Object.getProgram 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:161814:13)\n    at Project.updateGraphWorker 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:166861:53)\n    at Project.updateGraph 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:166790:42)\n    at ConfiguredProject.updateGraph 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:167825:63)\n    at Object.updateProjectIfDirty 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:168314:45)\n    at Project.getLanguageService 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:166404:28)\n    at Session.getCompletions 

(/usr/local/lib/node_modules/typescript/lib/tsserver.js:173418:43)\n    at Session.handlers.ts.Map.ts.getEntries._a.

<computed> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:172260:61)\n    at 

/usr/local/lib/node_modules/typescript/lib/tsserver.js:174067:88\n    at Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:174058:28)\n    at Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:174067:33)\n    at Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:174093:35)\n    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:176698:31)\n    at Interface.emit (node:events:527:28)\n    at [_onLine] [as _onLine] (node:internal/readline/interface:424:12)\n    at [_normalWrite] [as _normalWrite] (node:internal/readline/interface:613:59)\n    at Socket.ondata (node:internal/readline/interface:251:23)\n    at Socket.emit (node:events:527:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)"
   }
```

**Comment by zilongshanren** [comment]
重新安装 npm install -g typescript-language-server typescript 就好了
