### ISSUE TITLE
gopls signature help 解析出错

### ISSUE THREAD

**Issue by opsnull** [manateelazycat/lsp-bridge#207]
python signatureHelp 格式：
```
--- Recv response (858): textDocument/signatureHelp
{
   "jsonrpc": "2.0",
   "id": 858,
   "result": {
      "signatures": [
         {
            "label": "(__event: str, *args: Any) -> None",
            "parameters": [
               {
                  "label": "__event: str"
               },
               {
                  "label": "*args: Any"
               }
            ],
            "activeParameter": 0
         }
      ],
      "activeSignature": 0,
      "activeParameter": 0
   }
}
Eval in Emacs: (lsp-bridge-signature-help-update '("__event" "*args") '0)
```

但是 gopls signatureHelp 格式：
```
--- Recv response (36638): textDocument/signatureHelp
{
   "jsonrpc": "2.0",
   "result": {
      "signatures": [
         {
            "label": "Chmod(name string, mode os.FileMode) error",
            "documentation": "Chmod changes the mode of the named file to mode.\nIf the file is a symbolic link, it changes the mode of the link's target.\nIf there is an error, it will be of type *PathError.\n\nA different subset of the mode bits are used, depending on the\noperating system.\n\nOn Unix, the mode's permission bits, ModeSetuid, ModeSetgid, and\nModeSticky are used.\n\nOn Windows, only the 0200 bit (owner writable) of mode is used; it\ncontrols whether the file's read-only attribute is set or cleared.\nThe other bits are currently unused. For compatibility with Go 1.12\nand earlier, use a non-zero mode. Use mode 0400 for a read-only\nfile and 0600 for a readable+writable file.\n\nOn Plan 9, the mode's permission bits, ModeAppend, ModeExclusive,\nand ModeTemporary are used.\n",
            "parameters": [
               {
                  "label": "name string"
               },
               {
                  "label": "mode os.FileMode"
               }
            ]
         }
      ]
   },
   "id": 36638
}
Error when processing response 36638
Traceback (most recent call last):
  File "/Users/zhangjun/.emacs.d/straight/repos/lsp-bridge/core/handler/__init__.py", line 59, in handle_response
    self.process_response(response)
  File "/Users/zhangjun/.emacs.d/straight/repos/lsp-bridge/core/handler/signature_help.py", line 16, in process_response
    list(map(lambda p: p["label"].split(":")[0], response["signatures"][response["activeSignature"]]["parameters"])),
KeyError: 'activeSignature'
```

或者，带 activeParameter 的情况：
```
--- Recv response (39908): textDocument/signatureHelp
{
   "jsonrpc": "2.0",
   "result": {
      "signatures": [
         {
            "label": "Chmod(name string, mode os.FileMode) error",
            "documentation": "Chmod changes the mode of the named file to mode.\nIf the file is a symbolic link, it changes the mode of the link's target.\nIf there is an error, it will be of type *PathError.\n\nA different subset of the mode bits are used, depending on the\noperating system.\n\nOn Unix, the mode's permission bits, ModeSetuid, ModeSetgid, and\nModeSticky are used.\n\nOn Windows, only the 0200 bit (owner writable) of mode is used; it\ncontrols whether the file's read-only attribute is set or cleared.\nThe other bits are currently unused. For compatibility with Go 1.12\nand earlier, use a non-zero mode. Use mode 0400 for a read-only\nfile and 0600 for a readable+writable file.\n\nOn Plan 9, the mode's permission bits, ModeAppend, ModeExclusive,\nand ModeTemporary are used.\n",
            "parameters": [
               {
                  "label": "name string"
               },
               {
                  "label": "mode os.FileMode"
               }
            ]
         }
      ],
      "activeParameter": 1
   },
   "id": 39908
}
Error when processing response 39908
Traceback (most recent call last):
  File "/Users/zhangjun/.emacs.d/straight/repos/lsp-bridge/core/handler/__init__.py", line 59, in handle_response
    self.process_response(response)
  File "/Users/zhangjun/.emacs.d/straight/repos/lsp-bridge/core/handler/signature_help.py", line 16, in process_response
    list(map(lambda p: p["label"].split(":")[0], response["signatures"][response["activeSignature"]]["parameters"])),
KeyError: 'activeSignature'

```

或者，请求不带参数的函数：
```
--- Recv response (56993): textDocument/signatureHelp
{
   "jsonrpc": "2.0",
   "result": {
      "signatures": [
         {
            "label": "parse() error"
         }
      ]
   },
   "id": 56993
}
Error when processing response 56993
Traceback (most recent call last):
  File "/Users/zhangjun/.emacs.d/straight/repos/lsp-bridge/core/handler/__init__.py", line 59, in handle_response
    self.process_response(response)
  File "/Users/zhangjun/.emacs.d/straight/repos/lsp-bridge/core/handler/signature_help.py", line 16, in process_response
    list(map(lambda p: p["label"].split(":")[0], response["signatures"][response.get("activeSignature", 0)]["parameters"])),
KeyError: 'parameters'

```

$ gopls version
golang.org/x/tools/gopls v0.8.4
    golang.org/x/tools/gopls@v0.8.4 h1:zGZsAXAb0LLws/Z+2BCWR17dkPHhIO2GYwYSSkeXX5c=

**Comment by manateelazycat** [comment]
已经修复了。

**Comment by opsnull** [comment]
> 已经修复了。

大佬手速太快了。不过，你的这个修复不完整，还有可能出现  KeyError: 'parameters'、KeyError: 'activeParameter'  的情况。我上面的 PR 可以处理这几种情况。

**Comment by manateelazycat** [comment]
你重新基于最新版再提交个PR吧，感谢。

**Comment by opsnull** [comment]
> 你重新基于最新版再提交个PR吧，感谢。

已提：https://github.com/manateelazycat/lsp-bridge/pull/209
