### ISSUE TITLE
java 代码中执行 code action 错误

### ISSUE THREAD

**Issue by xqliu** [manateelazycat/lsp-bridge#252]
已经升级到当前最新版本，

报错信息

```

{'id': 27561, 'method': 'workspace/executeCommand', 'params': {'command': {'title': "Import 'Set' (java.util)", 'command': 'java.apply.workspaceEdit', 'arguments': [[Symbol(':changes'), [Symbol(':file:///Users/xxx/Documents/Hello.java'), [[Symbol(':range'), [Symbol(':start'), [Symbol(':line'), 0, Symbol(':character'), 0], Symbol(':end'), [Symbol(':line'), 25, Symbol(':character'), 25]], Symbol(':newText'), '\n\nimport java.util.Collection;\nimport java.util.Date;\nimport java.util.List;\nimport java.util.ArrayList;\nimport java.util.Objects;\nimport java.util.Set;']]]]]}, 'arguments': []}, 'jsonrpc': '2.0'}

--- Recv response (33272): textDocument/codeAction
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/xx/.emacs.d/.local/straight/repos/lsp-bridge/core/lspserver.py", line 103, in run
    self._send_message(message)
  File "/Users/xx/.emacs.d/.local/straight/repos/lsp-bridge/core/lspserver.py", line 81, in _send_message
    message_str = "Content-Length: {}\r\n\r\n{}".format(len(json.dumps(message)), json.dumps(message))
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Symbol is not JSON serializable
```

貌似在 java 代码中，M-x `lsp-bridge-code-action` 具体的 action 列表能够弹出，但是执行后实际上没有效果

比如下面的代码 

```
Set<String> set = new HashSet<>();
```

将鼠标放在 Set 上然后 M-x `lsp-bridge-code-action`，弹出的 action 列表是对的 

<img width="796" alt="image" src="https://user-images.githubusercontent.com/22554/177227759-ef0619ae-8dc1-4f29-93b9-112b78f08bb0.png">

但是选中第一个 action 后按回车，文件没有变化

**Comment by manateelazycat** [comment]
给一下测试的完整代码吧，我平常不写java

**Comment by manateelazycat** [comment]
最新版已经修复了， 如果还有问题请新建 issue.

**Comment by xqliu** [comment]
> 

抱歉没有看到，如下的代码可以重现 

(输入时候不自动导入，然后将鼠标放到 Set 上，运行 `lsp-bridge-code-action` 

```
public class Hello {
    public static final void main(String[] args) {
        Set<String> set = new HashSet<>();
    }
}
```

十分感谢修复
