### ISSUE TITLE
epc通信问题

### ISSUE THREAD

**Issue by luyajun01** [manateelazycat/lsp-bridge#481]
mac平台，emacs28，打开emacs报错：

```
Traceback (most recent call last):
  File "/Users/.emacs.d/site-lisp/lsp-bridge/lsp_bridge.py", line 374, in <module>
    LspBridge(sys.argv[1:])
  File "/Users/.emacs.d/site-lisp/lsp-bridge/lsp_bridge.py", line 57, in __init__
    init_epc_client(int(args[0]))
  File "/Users/.emacs.d/site-lisp/lsp-bridge/core/utils.py", line 72, in init_epc_client
    
  File "/Users/anaconda3/envs/myvenv/lib/python3.8/site-packages/epc/client.py", line 95, in __init__
    self.connect(socket_or_address)
  File "/Users/anaconda3/envs/myvenv/lib/python3.8/site-packages/epc/client.py", line 110, in connect
    self.socket = socket.create_connection(socket_or_address)
  File "/Users/anaconda3/envs/myvenv/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Users/anaconda3/envs/myvenv/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

Process *lsp-bridge* exited abnormally with code 1
```

问下这个问题如何解决？

**Comment by manateelazycat** [comment]
你是怎么安装的？

**Comment by luyajun01** [comment]
直接git clone最新的代码，按照您readme里的提示，也安装了所需的python包。

这是我的文件配置。

```
;; init-lsp-bridge
(add-to-list 'load-path "/Users/.emacs.d/site-lisp/lsp-bridge/")

(require 'yasnippet)
(yas-global-mode 1)
(require 'lsp-bridge)
(global-lsp-bridge-mode)

(setq lsp-bridge-python-command "/Users/anaconda3/envs/myvenv/bin/python")
(setq lsp-bridge-python-lsp-server "pyright")
```

这是我的pyright.json 配置文件
`{
  "name": "pyright",
  "languageId": "python",
  "command": [
    "pyright-langserver",
    "--stdio"
  ],
  "ignore-diagnostic": "# type: ignore",
  "settings": {
    "python.analysis": {
      "autoImportCompletions": true,
      "typeshedPaths": [],
      "stubPath": "",
      "useLibraryCodeForTypes": true,
      "diagnosticMode": "openFilesOnly",
      "typeCheckingMode": "basic",
      "logLevel": "verbose",
      "autoSearchPaths": true,
      "extraPaths": []
    },
    "pythonPath": "/Users/anaconda3/envs/myvenv/bin/python",
    "venvPath": "/Users/anaconda3/envs/myvenv"
  }
}
`

**Comment by manateelazycat** [comment]
应该是 anaconda3 的问题，你自己排查吧。
