### ISSUE TITLE
无法启动deno语言服务

### ISSUE THREAD

**Issue by cxb811201** [manateelazycat/lsp-bridge#542]
Traceback (most recent call last):
  File "/Users/xianbin/.emacs.d/.local/straight/build-29.0.60/lsp-bridge/lsp_bridge.py", line 139, in event_dispatcher
    getattr(self, func_name)(*func_args)
  File "/Users/xianbin/.emacs.d/.local/straight/build-29.0.60/lsp-bridge/lsp_bridge.py", line 340, in _do
    open_file_success = self._open_file(filepath)  # _do is called inside event_loop, so we can block here.
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xianbin/.emacs.d/.local/straight/build-29.0.60/lsp-bridge/lsp_bridge.py", line 218, in _open_file
    self.load_single_lang_server(project_path, filepath)
  File "/Users/xianbin/.emacs.d/.local/straight/build-29.0.60/lsp-bridge/lsp_bridge.py", line 231, in load_single_lang_server
    single_lang_server = get_emacs_func_result("get-single-lang-server", project_path, filepath)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xianbin/.emacs.d/.local/straight/repos/lsp-bridge/core/utils.py", line 144, in get_emacs_func_result
    result = epc_client.call_sync(method_name, args)    # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xianbin/Library/Python/3.11/lib/python/site-packages/epc/handler.py", line 402, in call_sync
    return self._blocking_request(self.call, timeout, name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xianbin/Library/Python/3.11/lib/python/site-packages/epc/handler.py", line 384, in _blocking_request
    return bc.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xianbin/Library/Python/3.11/lib/python/site-packages/epc/handler.py", line 116, in result
    raise reply
epc.handler.ReturnError: [Symbol('no-catch'), Symbol('--cl-block-nil--'), 'deno']

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/issues/528#issuecomment-1426928681

**Comment by manateelazycat** [comment]
你的deno源代码给一份看看内容？

**Comment by cxb811201** [comment]
@manateelazycat 不好意思，是我自己的问题
把lsp-bridge-get-single-lang-server-by-project中的dolist替换为cl-dolist，就正常了

**Comment by manateelazycat** [comment]
cl-dolls 要和 cl-return 配套用
