### ISSUE TITLE
自己添加了针对html和css的language server提示报错

### ISSUE THREAD

**Issue by zilongshanren** [manateelazycat/lsp-bridge#60]
https://github.com/hrsh7th/vscode-langservers-extracted

**Comment by zilongshanren** [comment]
错误信息晚点发上来

**Comment by zilongshanren** [comment]
```
Eval in Emacs: (lsp-bridge--first-start '53079)
Cache action change_cursor, wait for file /Users/lionqu/workspace/my-project-name/src/components/test.html to open it before executing.

--- Send request initialize: 16554
{
   "jsonrpc": "2.0",
   "method": "initialize",
   "params": {
      "processId": 69100,
      "rootPath": "/Users/lionqu/workspace/my-project-name",
      "clientInfo": {
         "name": "emacs",
         "version": "GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6)\n of 2022-04-04"
      },
      "rootUri": "file:///Users/lionqu/workspace/my-project-name",
      "capabilities": {},
      "initializationOptions": {}
   },
   "id": 16554
}

--- Recv message:  16554
{
   "jsonrpc": "2.0",
   "id": 16554,
   "result": {
      "capabilities": {
         "textDocumentSync": 2,
         "hoverProvider": true,
         "documentHighlightProvider": true,
         "documentRangeFormattingProvider": false,
         "documentFormattingProvider": false,
         "documentLinkProvider": {
            "resolveProvider": false
         },
         "documentSymbolProvider": true,
         "definitionProvider": true,
         "signatureHelpProvider": {
            "triggerCharacters": [
               "("
            ]
         },
         "referencesProvider": true,
         "colorProvider": {},
         "foldingRangeProvider": true,
         "selectionRangeProvider": true,
         "renameProvider": true,
         "linkedEditingRangeProvider": true
      }
   }
}
Traceback (most recent call last):
  File "/Users/lionqu/Github/lsp-bridge/core/lspserver.py", line 253, in lsp_message_dispatcher
    self.handle_recv_message(message["content"])
  File "/Users/lionqu/Github/lsp-bridge/core/lspserver.py", line 438, in handle_recv_message
    self.trigger_characters = message["result"]["capabilities"]["completionProvider"]["triggerCharacters"]
KeyError: 'completionProvider'

```

**Comment by zilongshanren** [comment]
(defcustom lsp-bridge-lang-server-extension-list
  '(
    (("vue") . "volar")
    (("html") . "vscode")
    (("css") . "vscode")
    )
  "The lang server rule for file extension."
  :type 'cons)

**Comment by zilongshanren** [comment]
```
{
  "name": "vscode",
  "languageId": "html",
  "command": [
    "vscode-html-language-server",
    "--stdio"
  ],
  "settings": {}
}

```

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/lsp-bridge/commit/256961dc14399bdf8f3f68d221467eaa092b8d4c
