### ISSUE TITLE
`lsp-bridge-workspace-list-symbols` result in KeyError: 'workspace_symbol'

### ISSUE THREAD

**Issue by sawyerzheng** [manateelazycat/lsp-bridge#600]
Using pyright + ruff, and call `lsp-bridge-workspace-list-symbols` will make no effect, and raise KeyError:

``` python
ERROR:epc:ReturnError([Symbol('invalid-function'), Symbol('lsp-bridge--with-file-buffer')])

Traceback (most recent call last):
  File "/home/sawyer/.emacs.d.clean/straight/repos/lsp-bridge/lsp_bridge.py", line 442, in event_dispatcher
    getattr(self, func_name)(*func_args)
  File "/home/sawyer/.emacs.d.clean/straight/repos/lsp-bridge/lsp_bridge.py", line 683, in _do
    action.call(name, *args)
  File "/home/sawyer/.emacs.d.clean/straight/repos/lsp-bridge/core/fileaction.py", line 157, in call
    method_server_names = [self.multi_servers_info[method]]
KeyError: 'workspace_symbol'
```
log content, after `(setq lsp-bridge-enable-debug t)`:
[log.txt](https://github.com/manateelazycat/lsp-bridge/files/11280068/log.txt)

**Comment by manateelazycat** [comment]
can you give me some test code？thanks

**Comment by sawyerzheng** [comment]
a simple function:
``` python
def hello():
    a = 3
    print(a)
```

![image](https://user-images.githubusercontent.com/44355570/233294583-c27cbe39-33c3-4977-ac3f-95c1fa9397ae.png)

**Comment by manateelazycat** [comment]
Please update to newst version, has fixed, thanks for report.

**Comment by sawyerzheng** [comment]
it do fixed and works well. Thank you.
