### ISSUE TITLE
更新到最新commit之后在windows无法使用

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#693]
更新到最新commit `d97f2b170600c5aa3eb309d505ade4828738512e`
lsp-bridge加载成功，但是服务器无法启动，无法使用

![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/ec60dbdd-ee7f-4522-93b3-d85c83dd4ae5)

`*lsp-bridge*`buffer报错如下，和新加的copilot支持有关
```
Traceback (most recent call last):
  File "c:\Users\Administrator\emacs-plugin\lsp-bridge\lsp_bridge.py", line 817, in <module>
    LspBridge(sys.argv[1:])
  File "c:\Users\Administrator\emacs-plugin\lsp-bridge\lsp_bridge.py", line 95, in __init__
    self.init_search_backends()
  File "c:\Users\Administrator\emacs-plugin\lsp-bridge\lsp_bridge.py", line 109, in init_search_backends
    self.copilot = Copilot()
                   ^^^^^^^^^
  File "c:\Users\Administrator\emacs-plugin\lsp-bridge\core\copilot.py", line 39, in __init__
    npm_prefix = subprocess.check_output(['npm', 'config', 'get', 'prefix'], universal_newlines=True).strip()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] ϵͳ Ҳ   ָ     ļ   
```
我本地直接执行这个命令是有结果的
```
PS C:\Users\Administrator> npm config get prefix
C:\Users\Administrator\AppData\Roaming\npm
```
测试了下，windows上用subprocess.check_output执行命令时，如果命令是bat脚本，需要写全名`npm.cmd`
```
PowerShell 7.3.6
PS C:\Users\Administrator> which npm
C:\Program Files\nodejs\npm.cmd
PS C:\Users\Administrator> python
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.check_output("npm config get prefix")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
>>> subprocess.check_output("npm.cmd config get prefix")
b'C:\\Users\\Administrator\\AppData\\Roaming\\npm\n'
>>>
```

**Comment by heheda123123** [comment]
测试了下，回退到commit `e959f3dd930dadb8b929a2ff5e93bb547e5ddb52`是可以正常工作的

**Comment by heheda123123** [comment]
另外看文档有启用copilot的函数，意味着默认应该是不启用copilot吧，没启用copilot的时候是不是可以不创建Copilot对象
```
File "c:\Users\Administrator\emacs-plugin\lsp-bridge\lsp_bridge.py", line 109, in init_search_backends
    self.copilot = Copilot()
```
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/9febb176-47ad-4b36-8e07-63573a72ea78)

**Comment by manateelazycat** [comment]
@kongds 看看?

**Comment by kongds** [comment]
已经修好了

**Comment by manateelazycat** [comment]
有问题随时打开，先关闭了
