### ISSUE TITLE
Always Waiting for Codeium local server to start

### ISSUE THREAD

**Issue by jenenliu** [manateelazycat/lsp-bridge#707]
Hello I fllow this guide, and everything is ok. But when I am trying to code, there's a message 
`[LSP-Bridge] Waiting for Codeium local server to start...
`
![image](https://github.com/manateelazycat/lsp-bridge/assets/5833520/6647e6dd-b46f-40f0-96e0-add918d34a9c)

And I can't find language-server process
```
➜  site-lisp git:(master) ✗ ps aux | grep language-server
jenenliu  278835  0.0  0.0  10076  2600 pts/1    S+   15:21   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox language-server

```

How can I fix this? thanks a lot.

**Comment by mumu-lhl** [comment]
This is not a problem. There will be no message when the local server is started. See
https://github.com/manateelazycat/lsp-bridge/blob/87d935d9c61688513be9f7223ee9a81ee9ad138a/core/codeium.py#L192-L218

Codeium completion should be available.

**Comment by jenenliu** [comment]
Hi @mumu-lhl , thanks for your reply.
I've checked the code, but I am sure codeium is not working, and language-server process has not started after a long time.
How can I start codeium manually by myself ?

**Comment by mumu-lhl** [comment]
Sorry, there is no way.

**Comment by finalclass** [comment]
I have similar problem. This is the *lsb-bridge* log:

```
I0529 13:05:24.455242 62232 main.go:284] Language server manager found random server port 35929
I0529 13:05:24.455311 62232 main.go:285] Language server manager found random lsp port 42101
I0529 13:05:24.455331 62232 main.go:292] Language server manager attempting to connect to language server at 127.0.0.1:35929
I0529 13:05:24.477012 62232 main.go:163] Fixing language server port at 35929
I0529 13:05:24.477034 62232 main.go:343] Language server manager successfully connected to new language server at 127.0.0.1:35929
HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/home/sel/Documents/configs/emacs/lsp-bridge/core/codeium.py", line 290, in post_request
    with urllib.request.urlopen(req) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by manateelazycat** [comment]
update newest and test again?
