### ISSUE TITLE
Can't rename C++ variable

### ISSUE THREAD

**Issue by ezchi** [manateelazycat/lsp-bridge#74]
Try to rename a variable in a C++ file, receive error as below

    --- Recv response (47120): textDocument/rename
    * Failed information about rename response.
    Traceback (most recent call last):
      File "/Users/foo/emacs-cfg/test-emacs/straight/repos/lsp-bridge/core/fileaction.py", line 278, in handle_rename_response
        (rename_file, rename_counter) = self.rename_symbol_in_file(rename_info)
      File "/Users/foo/emacs-cfg/test-emacs/straight/repos/lsp-bridge/core/fileaction.py", line 289, in rename_symbol_in_file
        rename_file = rename_info["textDocument"]["uri"]
    TypeError: string indices must be integers

**Comment by manateelazycat** [comment]
Hi, newest version has fixed issue, but looks clangd not return range is incomplete that rename operation won't replace all place.
