### ISSUE TITLE
Connection issues with lsp-bridge-enable-with-tramp and doom emacs

### ISSUE THREAD

**Issue by Bawaw** [manateelazycat/lsp-bridge#769]
Hey, thank you for this package, it is the best experience I've had with LSP in emacs so far!

However, while trying to integrate lsp-bridge in my daily workflow (doom emacs + remote pyright) I hit a block. When I `(setq lsp-bridge-enable-with-tramp 't)` I fail to connect to the LSP server when opening a file using tramp (see logs below). 

PS: When opening a remote file using `lsp-bridge-open-remote-file` everything works as expected. 

Details: 
- Ubuntu 22.04.3 LTS
- GNU Emacs 29.1
- Doom core     v3.0.0-pre
- Doom modules  v23.09.0-pre

```
Eval in Emacs: (lsp-bridge--first-start '60257)
Traceback (most recent call last):
  File "/home/bawaw/.lspbridge/lsp-bridge/lsp_bridge.py", line 180, in send_message_dispatcher
    client = self.get_socket_client(data["host"], port)
  File "/home/bawaw/.lspbridge/lsp-bridge/lsp_bridge.py", line 398, in get_socket_client
    self.host_names[server_host]["username"],
KeyError: 'remotehostname'

Traceback (most recent call last):
  File "/home/bawaw/.lspbridge/lsp-bridge/core/remote_file.py", line 63, in connect_ssh
    ssh.connect(self.ssh_host, port=self.ssh_port, username=self.ssh_user, key_filename=pub_key)
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: Int or String expected

Traceback (most recent call last):
  File "/home/bawaw/.lspbridge/lsp-bridge/core/remote_file.py", line 63, in connect_ssh
    ssh.connect(self.ssh_host, port=self.ssh_port, username=self.ssh_user, key_filename=pub_key)
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: Int or String expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bawaw/.lspbridge/lsp-bridge/core/remote_file.py", line 70, in connect_ssh
    ssh.connect(self.ssh_host, port=self.ssh_port, username=self.ssh_user, password=password)
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: Int or String expected

Exception in thread Thread-11 (sync_tramp_remote):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bawaw/.lspbridge/lsp-bridge/lsp_bridge.py", line 278, in sync_tramp_remote
    client = self.get_socket_client(server_host, REMOTE_FILE_ELISP_CHANNEL)
  File "/home/bawaw/.lspbridge/lsp-bridge/lsp_bridge.py", line 396, in get_socket_client
    client = RemoteFileClient(
  File "/home/bawaw/.lspbridge/lsp-bridge/core/remote_file.py", line 47, in __init__
    self.chan = self.transport.open_channel("direct-tcpip", (self.ssh_host, self.server_port), ('0.0.0.0', 0))
AttributeError: 'NoneType' object has no attribute 'open_channel'

```

**Comment by werhner** [comment]
The problem seems to be that lsp-bridge cannot get the remote hostname. Are you using the ssh protocol? If so, please provide the tramp path of the file and the ssh config file. Thanks.

**Comment by werhner** [comment]
This question seems similar to issue https://github.com/manateelazycat/lsp-bridge/issues/758. Is the host name defined in .ssh/config in domain name format rather than IP format?

**Comment by Bawaw** [comment]
The config is indeed defined in name format. However, I also tried using ip format: 
`/ssh:bawaw@x.x.x.x:/usr/local/project/main.py`

With config: 
```
Host x.x.x.x
  HostName x.x.x.x
  User bawaw
```

I get a slightly different error this time:
```
Traceback (most recent call last):
  File "/home/bawaw/.lspbridge/lsp-bridge/lsp_bridge.py", line 180, in send_message_dispatcher
    client = self.get_socket_client(data["host"], port)
  File "/home/bawaw/.lspbridge/lsp-bridge/lsp_bridge.py", line 398, in get_socket_client
    self.host_names[server_host]["username"],
KeyError: 'x.x.x.x'

Traceback (most recent call last):
  File "/home/bawaw/.lspbridge/lsp-bridge/core/remote_file.py", line 63, in connect_ssh
    ssh.connect(self.ssh_host, port=self.ssh_port, username=self.ssh_user, key_filename=pub_key)
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/client.py", line 788, in _auth
    key = self._key_from_filepath(
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/pkey.py", line 421, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/ed25519key.py", line 65, in __init__
    signing_key = self._parse_signing_key_data(data, password)
  File "/home/bawaw/.local/lib/python3.10/site-packages/paramiko/ed25519key.py", line 98, in _parse_signing_key_data
    raise PasswordRequiredException(
paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted


```

**Comment by werhner** [comment]
Please update to the latest version and then execute lsp-bridge-tramp-show-hostnames function. 
After that, check if the output of the host configuration options meets expectations. 
The HostName should be in the IP format.

**Comment by werhner** [comment]
According to the provided log, it seems that the issue lies in the encryption of the private key file. Paramiko raised a `PasswordRequiredException` exception. Is your key file encrypted?

**Comment by Bawaw** [comment]
Alright so removing the password from my private key circumvented the encryption problems but when I connect I still get the following error: 
\*messages\*: `or: Wrong type argument: lsp-bridge-epc-manager, nil`
\*lsp-bridge\*: `ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('stringp'), []])`

With logging enabled I now get: 
```
Eval in Emacs: (lsp-bridge--first-start '46367)
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('stringp'), []])
Eval in Emacs: (message '"[LSP-Bridge] Connect bawaw@x.x.x.x#22...")
Eval in Emacs: (lsp-bridge-update-tramp-file-info '"/ssh:bawaw@x.x.x.x:/usr/local/project/main.py"> '"x.x.x.x" '"/usr/local/project/main.py" '"/ssh:bawaw@x.x.x.x:")
```

I also noticed that in the following 3 scenario's the program behaves differently:

1. `lsp-bridge-open-remote-file` I get  `or: Wrong type argument: lsp-bridge-epc-manager, nil` and nothing happens.
2. When I first enable logging and then use `lsp-bridge-open-remote-file` I also get the epc error but the file does open.
3. When I first open a file using tramp and then use `lsp-bridge-open-remote-file` it also and I also get the epc error

The autocomplete also does not seem to be working when I'm using `lsp-bridge-open-remote-file`, I'm sorry for not noticing this earlier. I get the [LBR] file-name buffer but the autocomplete only returns some yas-snippets and search words.

**Comment by werhner** [comment]
In the opening tramp file, will the autocomplete return some yas-snippets or nothing at all?
Please provide the log of remote lsp-birdge process.

**Comment by Bawaw** [comment]
When I open the file using tramp I get the following logs: 
```
Eval in Emacs: (lsp-bridge--first-start '43967)
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('stringp'), []])
Eval in Emacs: (message '"[LSP-Bridge] Connect bcroqu0@x.x.x.x#22...")
Eval in Emacs: (lsp-bridge-update-tramp-file-info '"/ssh:bcroqu0@x.x.x.x:/usr/local/main.py" '"x.x.x.x" '"/usr/local/main.py" '"/ssh:bcroqu0@x.x.x.x:")
```

Autocomplete returns yas-snippets and search words:
![image](https://github.com/manateelazycat/lsp-bridge/assets/9692326/75d72411-a65f-479e-b3bd-cb3189be2041)

But no real lsp functionality:
![image](https://github.com/manateelazycat/lsp-bridge/assets/9692326/20e4ab4c-6ffa-4778-ac5d-7b3dbfba4bc0)

**Comment by werhner** [comment]
<img width="764" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/15964105/4e70b379-af2a-4cec-ad17-a51cad17adf4">

It seems that there are no issues with the SSH connection and LSP completion. The only problem is that your Emacs is not displaying the completion results. Can you open a local Python file to see if LSP completion results are displayed correctly?

Perhaps you can submit a new issue explaining the current problem to get more help. I am more familiar with the remote editing part, and apologize for not being able to provide more assistance with the display issue.

**Comment by Bawaw** [comment]
I think indeed think that this is a problem on the display side of things. I've noticed that sometimes I do get autocomplete, sometimes I get a different autocomplete and sometimes I do not get any completion. I'll play around with it a bit more and if I do not find the cause I'll create a new issue. 
![image](https://github.com/manateelazycat/lsp-bridge/assets/9692326/52734a5d-ecfb-498b-ac54-38a5fd8dd2a4)
![image](https://github.com/manateelazycat/lsp-bridge/assets/9692326/5ae7e64d-4667-4120-b601-f010ec3f8160)
![image](https://github.com/manateelazycat/lsp-bridge/assets/9692326/dc4808b3-12b9-4c91-8076-8a3908521900)

There is one more problem on the remote connect side of things though (I think). When I open a file using tramp and I do not set `lsp-bridge-enable-log` I never get real autocomplete and the server does not build a connection. 

![image](https://github.com/manateelazycat/lsp-bridge/assets/9692326/b9319a2d-d139-40b0-80d0-81d2fd6bde34)

Sever log: 
`* Running lsp-bridge in remote server, use command 'lsp-bridge-open-remote-file' to open remote file.`

**Comment by manateelazycat** [comment]
Uncomment https://github.com/manateelazycat/lsp-bridge/blob/aed6415264bfa5bc83656cc8f5167b4a08f635fe/lsp-bridge.el#L1179

Will know why lsp-bridge-try-completion will failed.

**Comment by manateelazycat** [comment]
I commit https://github.com/manateelazycat/lsp-bridge/commit/a5651303a3b4b7368e08e381dc0e39cd9e8e9742

You can turn on lsp-bridge-enable-log, lsp-bridge will print debug message for completion predicate result, if result is nil, that's why completion menu not popup.

**Comment by manateelazycat** [comment]
Did you test with emacs -Q?

I guess other package in Doom will conflict with lsp-bridge.
