### ISSUE TITLE
Code action 列表太长后， code action menu 显示不全

### ISSUE THREAD

**Issue by manateelazycat** [manateelazycat/lsp-bridge#773]
![截图 2023-11-11 17-43-39](https://github.com/manateelazycat/lsp-bridge/assets/237487/2a152b0d-bc39-4061-a9c7-e9f1cae640c4)

重现方式：
1. 打开文件 /home/andy/lazycat-emacs/site-lisp/extensions/lspbridge/core/handler/__init__.py
2. 光标移动到底部， 会看到底部这一块的 import 语句都有警告
3. 移动到警告处， 执行  lsp-bridge-code-action
4. 因为诊断太多了， 导致菜单显示不全

**Comment by manateelazycat** [comment]
@kongds 大佬， 有空可以帮忙修复一下这个 issue 吗？ 谢谢

**Comment by kongds** [comment]
好的 等我忙完这阵子 修一下

**Comment by kongds** [comment]
我没法弹出这个，好像现在code action没有兼容ruff
```
Failed to handle request 32839 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///Users/royokong/lsp-bridge/core/handler/__init__.py'), range=45:36-45:46, context=CodeActionContext(diagnostics=[Diagnostic(range=45:36-45:46, message='`core.handler.completion.Completion` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 47}, 'location': {'column': 1, 'row': 46}}], 'message': 'Remove unused import: `core.handler.completion.Completion`'}), Diagnostic(range=46:41-46:55, message='`core.handler.completion_item.CompletionItem` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 48}, 'location': {'column': 1, 'row': 47}}], 'message': 'Remove unused import: `core.handler.completion_item.CompletionItem`'}), Diagnostic(range=47:37-47:47, message='`core.handler.find_define.FindDefine` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 49}, 'location': {'column': 1, 'row': 48}}], 'message': 'Remove unused import: `core.handler.find_define.FindDefine`'}), Diagnostic(range=48:42-48:56, message='`core.handler.find_type_define.FindTypeDefine` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 50}, 'location': {'column': 1, 'row': 49}}], 'message': 'Remove unused import: `core.handler.find_type_define.FindTypeDefine`'}), Diagnostic(range=49:45-49:63, message='`core.handler.find_implementation.FindImplementation` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 51}, 'location': {'column': 1, 'row': 50}}], 'message': 'Remove unused import: `core.handler.find_implementation.FindImplementation`'}), Diagnostic(range=50:41-50:55, message='`core.handler.find_references.FindReferences` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 52}, 'location': {'column': 1, 'row': 51}}], 'message': 'Remove unused import: `core.handler.find_references.FindReferences`'}), Diagnostic(range=51:30-51:44, message='`core.handler.peek.PeekFindDefine` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 53}, 'location': {'column': 1, 'row': 52}}], 'message': 'Remove unused import'}), Diagnostic(range=51:46-51:64, message='`core.handler.peek.PeekFindReferences` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 53}, 'location': {'column': 1, 'row': 52}}], 'message': 'Remove unused import'}), Diagnostic(range=52:31-52:36, message='`core.handler.hover.Hover` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 54}, 'location': {'column': 1, 'row': 53}}], 'message': 'Remove unused import: `core.handler.hover.Hover`'}), Diagnostic(range=53:40-53:53, message='`core.handler.signature_help.SignatureHelp` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 55}, 'location': {'column': 1, 'row': 54}}], 'message': 'Remove unused import: `core.handler.signature_help.SignatureHelp`'}), Diagnostic(range=54:40-54:53, message='`core.handler.prepare_rename.PrepareRename` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 56}, 'location': {'column': 1, 'row': 55}}], 'message': 'Remove unused import: `core.handler.prepare_rename.PrepareRename`'}), Diagnostic(range=55:32-55:38, message='`core.handler.rename.Rename` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 57}, 'location': {'column': 1, 'row': 56}}], 'message': 'Remove unused import: `core.handler.rename.Rename`'}), Diagnostic(range=56:42-56:56, message='`core.handler.jdt_uri_resolver.JDTUriResolver` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 58}, 'location': {'column': 1, 'row': 57}}], 'message': 'Remove unused import: `core.handler.jdt_uri_resolver.JDTUriResolver`'}), Diagnostic(range=57:43-57:58, message='`core.handler.deno_uri_resolver.DenoUriResolver` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 59}, 'location': {'column': 1, 'row': 58}}], 'message': 'Remove unused import: `core.handler.deno_uri_resolver.DenoUriResolver`'}), Diagnostic(range=58:37-58:47, message='`core.handler.code_action.CodeAction` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 60}, 'location': {'column': 1, 'row': 59}}], 'message': 'Remove unused import: `core.handler.code_action.CodeAction`'}), Diagnostic(range=59:36-59:46, message='`core.handler.formatting.Formatting` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 61}, 'location': {'column': 1, 'row': 60}}], 'message': 'Remove unused import: `core.handler.formatting.Formatting`'}), Diagnostic(range=60:41-60:55, message='`core.handler.execute_command.ExecuteCommand` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 62}, 'location': {'column': 1, 'row': 61}}], 'message': 'Remove unused import: `core.handler.execute_command.ExecuteCommand`'}), Diagnostic(range=61:42-61:57, message='`core.handler.workspace_symbol.WorkspaceSymbol` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 63}, 'location': {'column': 1, 'row': 62}}], 'message': 'Remove unused import: `core.handler.workspace_symbol.WorkspaceSymbol`'}), Diagnostic(range=62:40-62:73, message='`core.handler.call_hierarchy.PrepareCallHierarchyIncomingCalls` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 64}, 'location': {'column': 1, 'row': 63}}], 'message': 'Remove unused import'}), Diagnostic(range=62:75-62:108, message='`core.handler.call_hierarchy.PrepareCallHierarchyOutgoingCalls` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 64}, 'location': {'column': 1, 'row': 63}}], 'message': 'Remove unused import'}), Diagnostic(range=62:110-62:136, message='`core.handler.call_hierarchy.CallHierarchyIncomingCalls` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 64}, 'location': {'column': 1, 'row': 63}}], 'message': 'Remove unused import'}), Diagnostic(range=62:138-62:164, message='`core.handler.call_hierarchy.CallHierarchyOutgoingCalls` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 64}, 'location': {'column': 1, 'row': 63}}], 'message': 'Remove unused import'}), Diagnostic(range=63:41-63:55, message='`core.handler.document_symbol.DocumentSymbol` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 65}, 'location': {'column': 1, 'row': 64}}], 'message': 'Remove unused import: `core.handler.document_symbol.DocumentSymbol`'}), Diagnostic(range=64:62-64:89, message='`core.handler.jdtls.jdtls_list_overridable_methods.JdtlsListOverridableMethods` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 66}, 'location': {'column': 1, 'row': 65}}], 'message': 'Remove unused import: `core.handler.jdtls.jdtls_list_overridable_methods.JdtlsListOverridableMethods`'}), Diagnostic(range=65:61-65:87, message='`core.handler.jdtls.jdtls_add_overridable_methods.JdtlsAddOverridableMethods` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 67}, 'location': {'column': 1, 'row': 66}}], 'message': 'Remove unused import: `core.handler.jdtls.jdtls_add_overridable_methods.JdtlsAddOverridableMethods`'}), Diagnostic(range=66:36-66:45, message='`core.handler.inlay_hint.InlayHint` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 68}, 'location': {'column': 1, 'row': 67}}], 'message': 'Remove unused import: `core.handler.inlay_hint.InlayHint`'}), Diagnostic(range=67:41-67:55, message='`core.handler.semantic_tokens.SemanticTokens` imported but unused', severity=<DiagnosticSeverity.Warning: 2>, code='F401', code_description=None, source='Ruff', tags=[<DiagnosticTag.Unnecessary: 1>], related_information=None, data={'applicability': 'Automatic', 'edits': [{'content': '', 'end_location': {'column': 1, 'row': 69}, 'location': {'column': 1, 'row': 68}}], 'message': 'Remove unused import: `core.handler.semantic_tokens.SemanticTokens`'})], only=None, trigger_kind=None), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/pygls/protocol.py", line 337, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/opt/homebrew/lib/python3.10/site-packages/pygls/protocol.py", line 261, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/opt/homebrew/lib/python3.10/site-packages/ruff_lsp/server.py", line 409, in code_action
    edit=_create_workspace_edit(
  File "/opt/homebrew/lib/python3.10/site-packages/ruff_lsp/server.py", line 533, in _create_workspace_edit
    line=fix["location"]["row"] - 1,
KeyError: 'location'
Recv message (error):
{
   "error": {
      "code": -32602,
      "message": "KeyError: 'location'",
      "data": "{'traceback': ['  File \"/opt/homebrew/lib/python3.10/site-packages/pygls/protocol.py\", line 337, in _handle_request\\n    self._execute_request(msg_id, handler, params)\\n', '  File \"/opt/homebrew/lib/python3.10/site-packages/pygls/protocol.py\", line 261, in _execute_request\\n    self._send_response(msg_id, handler(params))\\n', '  File \"/opt/homebrew/lib/python3.10/site-packages/ruff_lsp/server.py\", line 409, in code_action\\n    edit=_create_workspace_edit(\\n', '  File \"/opt/homebrew/lib/python3.10/site-packages/ruff_lsp/server.py\", line 533, in _create_workspace_edit\\n    line=fix[\"location\"][\"row\"] - 1,\\n']}"
   },
   "jsonrpc": "2.0",
   "id": 32839
}
```

**Comment by manateelazycat** [comment]
ruff版本原因？

**Comment by kongds** [comment]
我用的版本是ruff==0.0.292 试了下新版的ruff(0.1.0+) 现在的lsp-bridge好像并不支持
```
[LSP-Bridge] pubmedqa_llama (ruff): error: unexpected argument ’--format’ found

  tip: to pass ’--format’ as a value, use ’-- --format’

Usage: ruff check <FILES|--fix|--no-fix|--unsafe-fixes|--no-unsafe-fixes|--show-source|--no-show-source|--show-fixes|--no-show-fixes|--diff|--watch|--fix-only|--no-fix-only|--ignore-noqa|--output-format <OUTPUT_FORMAT>|--output-file <OUTPUT_FILE>|--target-version <TARGET_VERSION>|--preview|--no-preview|--config <CONFIG>|--select <RULE_CODE>|--ignore <RULE_CODE>|--extend-select <RULE_CODE>|--extend-ignore <RULE_CODE>|--per-file-ignores <PER_FILE_IGNORES>|--extend-per-file-ignores <EXTEND_PER_FILE_IGNORES>|--exclude <FILE_PATTERN>|--extend-exclude <FILE_PATTERN>|--fixable <RULE_CODE>|--unfixable <RULE_CODE>|--extend-fixable <RULE_CODE>|--extend-unfixable <RULE_CODE>|--respect-gitignore|--no-respect-gitignore|--force-exclude|--no-force-exclude|--line-length <LINE_LENGTH>|--dummy-variable-rgx <DUMMY_VARIABLE_RGX>|--no-cache|--isolated|--cache-dir <CACHE_DIR>|--stdin-filename <STDIN_FILENAME>|--exit-zero|--exit-non-zero-on-fix|--statistics|--add-noqa|--show-files|--show-settings|--ecosystem-ci> <--verbose|--quiet|--silent>

For more information, try ’--help’.
```

**Comment by manateelazycat** [comment]
> 我用的版本是ruff==0.0.292 试了下新版的ruff(0.1.0+) 现在的lsp-bridge好像并不支持
> 
> ```
> [LSP-Bridge] lsp-bridge (ruff): error: unexpected argument ’--format’ found
> 
>   tip: to pass ’--format’ as a value, use ’-- --format’
> 
> Usage: ruff check <FILES|--fix|--no-fix|--unsafe-fixes|--no-unsafe-fixes|--show-source|--no-show-source|--show-fixes|--no-show-fixes|--diff|--watch|--fix-only|--no-fix-only|--ignore-noqa|--output-format <OUTPUT_FORMAT>|--output-file <OUTPUT_FILE>|--target-version <TARGET_VERSION>|--preview|--no-preview|--config <CONFIG>|--select <RULE_CODE>|--ignore <RULE_CODE>|--extend-select <RULE_CODE>|--extend-ignore <RULE_CODE>|--per-file-ignores <PER_FILE_IGNORES>|--extend-per-file-ignores <EXTEND_PER_FILE_IGNORES>|--exclude <FILE_PATTERN>|--extend-exclude <FILE_PATTERN>|--fixable <RULE_CODE>|--unfixable <RULE_CODE>|--extend-fixable <RULE_CODE>|--extend-unfixable <RULE_CODE>|--respect-gitignore|--no-respect-gitignore|--force-exclude|--no-force-exclude|--line-length <LINE_LENGTH>|--dummy-variable-rgx <DUMMY_VARIABLE_RGX>|--no-cache|--isolated|--cache-dir <CACHE_DIR>|--stdin-filename <STDIN_FILENAME>|--exit-zero|--exit-non-zero-on-fix|--statistics|--add-noqa|--show-files|--show-settings|--ecosystem-ci> <--verbose|--quiet|--silent>
> 
> For more information, try ’--help’.
> ```

大佬， 你的 lsp-bridge 的版本是不是太低了， ruff 的 --format 参数我已经在一个月前已经移除了， 兼容最新的 ruff

**Comment by kongds** [comment]
我应该用的是最新的 我去看看是不是我的配置有问题
```
commit 867409997d46a5ecffbaa3e6751b1124c32d7b71 (HEAD -> master, origin/master, origin/HEAD)
Merge: 8d64a8a 1cb1b76
Author: Andy Stewart <lazycat.manatee@gmail.com>
Date:   Mon Nov 27 12:34:58 2023 +0800

    Merge pull request #795 from YusongWang/fix-typo

    fix typo lsp-brige to lsp-bridge
```

**Comment by kongds** [comment]
之前应该是我只升级ruff 忘记升级ruff-lsp了 😂

我在#797 修改了一下

**Comment by manateelazycat** [comment]
大佬， 已经更新， 太帅了。 ;)
