### ISSUE TITLE
能否添加一个获取inlayhints的命令

### ISSUE THREAD

**Issue by getong** [manateelazycat/lsp-bridge#775]
我在跟踪kotlin的inlayhints的问题，最后发现可能是因为lsp-mode是单独获取inlayhints的信息，这有可能导致lsp-bridge不能获取kotlin-language-server 的inlayhints信息。

lsp-mode获取inlayhints信息主要有两步
```
1 开启lsp-mode
2 开启lsp-inlay-hints-mode。 这里调用了lsp-update-inlay-hints函数，主要是一个lsp-request-async，在异步返回中处理返回结果。
代码可以看这里：
https://github.com/emacs-lsp/lsp-mode/blob/4c93d3c87174e6fdbe1b760f3f27aa71ecdc1d4e/lsp-mode.el#L9647C1-L9672C1
```

但跟踪了一下lsp-bridge的代码，有可能因为启动过程中某些步骤失败了，从而没有发出获取inlay-hints信息的指令。(个人对python和elisp不熟悉，可能对代码理解错误)

所以能不能单独设置个命令获取inlay hints 信息？

**Comment by manateelazycat** [comment]
现在是自动发送的 https://github.com/manateelazycat/lsp-bridge/blob/c6d05653f8325684ea64c0d0d06523be5c219320/lsp-bridge.el#L1431

要看lsp server是否支持inlay，并返回inlay消息，可以打开log选项就知道lsp server是否有返回消息

**Comment by getong** [comment]
kotlin-language-server 日志
```
Command "semgrep lsp" is not present on the path.
Command "/Users/gerald/test/kotlin/kotlin-language-server/server/build/install/server/bin/kotlin-language-server" is present on the path.
Command "semgrep lsp" is not present on the path.
Command "/Users/gerald/test/kotlin/kotlin-language-server/server/build/install/server/bin/kotlin-language-server" is present on the path.
Found the following clients for /Users/gerald/test/kotlin/h5/app/src/main/kotlin/h5/app/App.kt: (server-id kotlin-ls, priority -1)
The following clients were selected based on priority: (server-id kotlin-ls, priority -1)
main      Adding script definitions [null]
main      Kotlin Language Server: Version 1.3.8
main      A delegate object is null, jsonrpc methods of 'public default org.eclipse.lsp4j.services.NotebookDocumentService org.eclipse.lsp4j.services.LanguageServer.getNotebookDocumentService()' are ignored
main      Connected to client
async0    Database has version 0 != 3 (the required version), therefore it will be rebuilt...
async0    Adding workspace folder null
async0    Adding .../app/App.kt, .../app/MessageUtils.kt under /Users/gerald/test/kotlin/h5/app/src/main/kotlin/h5/app to source path
async0    Searching for dependencies and Java sources in workspace root /Users/gerald/test/kotlin/h5/app/src/main/kotlin/h5/app
async0    Found kotlinc at /usr/local/bin/kotlinc
async0    Found Kotlin CLI compiler library kotlin-stdlib at /usr/local/Cellar/kotlin/1.9.20/libexec/lib/kotlin-stdlib.jar
async0    Adding [/usr/local/Cellar/kotlin/1.9.20/libexec/lib/kotlin-stdlib.jar] to class path
async0    Update build script path
async1    Found kotlinc at /usr/local/bin/kotlinc
async0    Found kotlinc at /usr/local/bin/kotlinc
async1    Found Kotlin CLI compiler library kotlin-stdlib at /usr/local/Cellar/kotlin/1.9.20/libexec/lib/kotlin-stdlib.jar
async0    Found Kotlin CLI compiler library kotlin-stdlib at /usr/local/Cellar/kotlin/1.9.20/libexec/lib/kotlin-stdlib.jar
async0    Adding [/usr/local/Cellar/kotlin/1.9.20/libexec/lib/kotlin-stdlib.jar] to build script class path
async0    Reinstantiating compiler
async0    Adding script definitions [null]
async0    Adding script definitions [null]
client    Updated configuration: {"kotlin":{"externalSources":{"autoConvertToKotlin":true,"useKlsScheme":true},"debugAdapter":{"path":"","enabled":true},"completion":{"snippets":{"enabled":true}},"linting":{"debounceTime":250},"compiler":{"jvm":{"target":"1.8"}},"trace":{"server":"off"},"languageServer":{"path":"kotlin-language-server"},"inlayHints":{"typeHints":true,"parameterHints":true,"chainedHints":true}}}
debounce1 Linting .../app/App.kt
async2    Find symbols in .../app/App.kt
async2    Finished in 57 ms
async3    Updating symbol index...
async3    Updated symbol index in 15 ms! (1 symbol(s))
async3    Updating symbol index...
async3    Updated symbol index in 1 ms! (2 symbol(s))
debounce1 Reported 5 diagnostics in .../app/App.kt
async3    Updating symbol index...
async3    Updated symbol index in 1 ms! (3 symbol(s))
org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Failed to generate expression: KtBlockExpression
File being compiled: (10,12) in //Users/gerald/test/kotlin/h5/app/src/main/kotlin/h5/app/App.kt
The root cause java.lang.IllegalStateException was thrown at: org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$typeMappingConfiguration$1.processErrorType(KotlinTypeMapper.kt:124)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:356)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genStatement(ExpressionCodegen.java:455)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:412)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:1840)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:64)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:86)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:637)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:481)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:261)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:166)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:137)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:200)
	at org.jetbrains.kotlin.codegen.PackagePartCodegen.generateBody(PackagePartCodegen.java:98)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:132)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:167)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:70)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:143)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.invokeLowerings(CodegenFactory.kt:122)
	at org.jetbrains.kotlin.codegen.CodegenFactory.generateModule(CodegenFactory.kt:44)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:45)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:54)
	at org.javacs.kt.compiler.Compiler.generateCode(Compiler.kt:585)
	at org.javacs.kt.SourcePath.save(SourcePath.kt:277)
	at org.javacs.kt.SourcePath.saveAllFiles(SourcePath.kt:289)
	at org.javacs.kt.KotlinTextDocumentService$lintAll$1.invoke(KotlinTextDocumentService.kt:276)
	at org.javacs.kt.KotlinTextDocumentService$lintAll$1.invoke(KotlinTextDocumentService.kt:274)
	at org.javacs.kt.util.Debouncer.submitImmediately$lambda$1(Debouncer.kt:27)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Error type encountered: [Error type: Return type for function cannot be resolved] (ErrorType).
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$typeMappingConfiguration$1.processErrorType(KotlinTypeMapper.kt:124)
	at org.jetbrains.kotlin.load.kotlin.DescriptorBasedTypeSignatureMappingKt.mapType(descriptorBasedTypeSignatureMapping.kt:83)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.kt:276)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType$default(KotlinTypeMapper.kt:267)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.kt)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.asmType(ExpressionCodegen.java:511)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.getVariableTypeNoSharing(ExpressionCodegen.java:1406)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.getVariableType(ExpressionCodegen.java:1387)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putLocalVariableIntoFrameMap(ExpressionCodegen.java:1436)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putDescriptorIntoFrameMap(ExpressionCodegen.java:1419)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateBlock(ExpressionCodegen.java:1327)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateBlock(ExpressionCodegen.java:1281)
	at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitBlockExpression(CodegenStatementVisitor.java:56)
	at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitBlockExpression(CodegenStatementVisitor.java:22)
	at org.jetbrains.kotlin.psi.KtBlockExpression.accept(KtBlockExpression.java:79)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:334)
	... 32 more
async3    Updating full symbol index...
async2    Hovering at .../app/App.kt 12:5
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering PROPERTY
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 149 ms
async2    Hovering at .../app/App.kt 12:9
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering PROPERTY
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 223 ms
async2    Hovering at .../app/App.kt 12:16
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering PROPERTY
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 658 ms
async2    Hovering at .../app/App.kt 12:18
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering DOT_QUALIFIED_EXPRESSION
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 152 ms
async2    Hovering at .../app/App.kt 12:30
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering DOT_QUALIFIED_EXPRESSION
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 155 ms
async2    Hovering at .../app/App.kt 12:35
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering REFERENCE_EXPRESSION
async2    Re-parsing App.kt 11:5-12:42
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 95 ms
..worker-1Updated full symbol index in 7429 ms! (17976 symbol(s))
async2    Hovering at .../app/App.kt 12:5
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering PROPERTY
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 46 ms
async2    Hovering at .../app/App.kt 12:9
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering PROPERTY
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 37 ms
async2    Hovering at .../app/App.kt 12:16
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering PROPERTY
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 37 ms
async2    Hovering at .../app/App.kt 12:18
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering DOT_QUALIFIED_EXPRESSION
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 26 ms
async2    Hovering at .../app/App.kt 12:30
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering DOT_QUALIFIED_EXPRESSION
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 26 ms
async2    Hovering at .../app/App.kt 12:35
async2    Re-parsing App.kt 11:5-12:42
async2    Hovering REFERENCE_EXPRESSION
async2    Re-parsing App.kt 11:5-12:42
async2    Re-parsing App.kt 11:5-12:42
async2    Finished in 23 ms

```

**Comment by getong** [comment]
lsp-log: kotlin-ls 日志
```
[Trace - 07:26:27 下午] Sending request 'initialize - (1)'.
Params: {
  "processId": 45718,
  "rootPath": "/Users/gerald/test/kotlin/h5/app/src/main/kotlin/h5/app",
  "clientInfo": {
    "name": "emacs",
    "version": "GNU Emacs 29.1 (build 1, x86_64-apple-darwin22.6.0, NS appkit-2299.70 Version 13.5 (Build 22G74))\n of 2023-08-04"
  },
  "rootUri": "file:///Users/gerald/test/kotlin/h5/app/src/main/kotlin/h5/app",
  "capabilities": {
    "general": {
      "positionEncodings": [
        "utf-32",
        "utf-16"
      ]
    },
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "workspaceFolders": true,
      "configuration": true,
      "codeLens": {
        "refreshSupport": true
      },
      "fileOperations": {
        "didCreate": false,
        "willCreate": false,
        "didRename": true,
        "willRename": true,
        "didDelete": false,
        "willDelete": false
      }
    },
    "textDocument": {
      "declaration": {
        "dynamicRegistration": true,
        "linkSupport": true
      },
      "definition": {
        "dynamicRegistration": true,
        "linkSupport": true
      },
      "references": {
        "dynamicRegistration": true
      },
      "implementation": {
        "dynamicRegistration": true,
        "linkSupport": true
      },
      "typeDefinition": {
        "dynamicRegistration": true,
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "onTypeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true,
        "prepareSupport": true
      },
      "codeAction": {
        "dynamicRegistration": true,
        "isPreferredSupport": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        },
        "resolveSupport": {
          "properties": [
            "edit",
            "command"
          ]
        },
        "dataSupport": true
      },
      "completion": {
        "completionItem": {
          "snippetSupport": false,
          "documentationFormat": [
            "markdown",
            "plaintext"
          ],
          "resolveAdditionalTextEditsSupport": true,
          "insertReplaceSupport": true,
          "deprecatedSupport": true,
          "resolveSupport": {
            "properties": [
              "documentation",
              "detail",
              "additionalTextEdits",
              "command"
            ]
          },
          "insertTextModeSupport": {
            "valueSet": [
              1,
              2
            ]
          }
        },
        "contextSupport": true,
        "dynamicRegistration": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        },
        "dynamicRegistration": true
      },
      "documentLink": {
        "dynamicRegistration": true,
        "tooltipSupport": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ],
        "dynamicRegistration": true
      },
      "foldingRange": {
        "dynamicRegistration": true
      },
      "selectionRange": {
        "dynamicRegistration": true
      },
      "callHierarchy": {
        "dynamicRegistration": false
      },
      "typeHierarchy": {
        "dynamicRegistration": true
      },
      "publishDiagnostics": {
        "relatedInformation": true,
        "tagSupport": {
          "valueSet": [
            1,
            2
          ]
        },
        "versionSupport": true
      },
      "linkedEditingRange": {
        "dynamicRegistration": true
      }
    },
    "window": {
      "workDoneProgress": true,
      "showDocument": {
        "support": true
      }
    }
  },
  "initializationOptions": null,
  "workDoneToken": "1"
}
```

**Comment by manateelazycat** [comment]
还有返回inlay得日志

**Comment by getong** [comment]
我反复启用 lsp-inlay-hints-mode, 只得到：
```
async2    Re-parsing App.kt 9:1-18:2
async2    Hovering BLOCK
```

**Comment by manateelazycat** [comment]
可以找到 lsp-mode 相关代码， 增加 message 语句， 就可以知道 inlay 返回结构， 我需要明确 kotlin 的返回结构是否和 rust 一样

**Comment by getong** [comment]
我加了
```
(message res)
```
得到的返回有很多，差不多是相同的，这是一个例子
```
[2023-11-13T19:43:28.678364] Error processing message (wrong-type-argument stringp (#s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("position" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("line" 13 "character" 18)) "label" "String" "kind" 1 "paddingLeft" t "paddingRight" t)) #s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("position" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("line" 14 "character" 12)) "label" "message:" "kind" 2 "paddingLeft" t "paddingRight" t)) #s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("position" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("line" 15 "character" 18)) "label" "Int" "kind" 1 "paddingLeft" t "paddingRight" t)) #s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("position" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("line" 16 "character" 12)) "label" "message:" "kind" 2 "paddingLeft" t "paddingRight" t)))).
```

**Comment by getong** [comment]
kotlin 代码例子是这样的：
```
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package h5.app

import h5.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
    val abc_string = "hell world"
    println(abc_string)
    val number_int = 1
    println(number_int)
}

```

**Comment by manateelazycat** [comment]
> 我加了
> 
> ```
> (message res)
> ```
> 
> 得到的返回有很多，差不多是相同的，这是一个例子
> 
> ```
> [2023-11-13T19:43:28.678364] Error processing message (wrong-type-argument stringp (#s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("position" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("line" 13 "character" 18)) "label" "String" "kind" 1 "paddingLeft" t "paddingRight" t)) #s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("position" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("line" 14 "character" 12)) "label" "message:" "kind" 2 "paddingLeft" t "paddingRight" t)) #s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("position" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("line" 15 "character" 18)) "label" "Int" "kind" 1 "paddingLeft" t "paddingRight" t)) #s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("position" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("line" 16 "character" 12)) "label" "message:" "kind" 2 "paddingLeft" t "paddingRight" t)))).
> ```

要用 (message "%s" res)

**Comment by getong** [comment]
返还很多次，截取一个例子：
```
[2023-11-13T19:56:50.421453] (#s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data (position #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 13 character 18)) label String kind 1 paddingLeft t paddingRight t)) #s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data (position #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 14 character 12)) label message: kind 2 paddingLeft t paddingRight t)) #s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data (position #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 15 character 18)) label Int kind 1 paddingLeft t paddingRight t)) #s(hash-table size 5 test equal rehash-size 1.5 rehash-threshold 0.8125 data (position #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 16 character 12)) label message: kind 2 paddingLeft t paddingRight t)))
```

**Comment by manateelazycat** [comment]
Rust lsp server 会明确的返回 inlayHintsProvider = True 的信息， Kotlin lsp server 不会。

lsp-bridge/lspserver.py 的 inlay_hint_provider 选项会根据 lsp server 返回的 inlayHintsProvider 为True 时更新 inlay_hint_provider 的值为 True, 我强制打开这个选项 https://github.com/manateelazycat/lsp-bridge/blob/29cc7a0a67d52fe363a75ea0e040fe1f63fa275f/core/lspserver.py#L223 然后强制发送 (lsp-bridge-try-send-inlay-hint-request) ， 这样可以强制发送 inlay-hint request 给 kotlin lsp server, 这时候 kotlin lsp server 会返回下面的错误。

Recv message (error):
{
   "jsonrpc": "2.0",
   "id": 11143,
   "error": {
      "code": -32603,
      "message": "Internal error.",
      "data": "java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\n\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)\n\t... 11 more\nCaused by: java.lang.UnsupportedOperationException\n\tat org.eclipse.lsp4j.services.TextDocumentService.inlayHint(TextDocumentService.java:653)\n\t... 16 more\n"
   }
}

默认的状态， 因为 kotlin lsp server 根本就不在初始化的时候返回 inlayHintProvider 能力， 所以 lsp-bridge 也不会发送 inlay hint 请求给 kotlin lsp server

我的环境：
 java --version
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9)
OpenJDK 64-Bit Server VM (build 11.0.21+9, mixed mode)

kotlin lsp server 是从 https://aur.archlinux.org/packages/kotlin-language-server 这里安装的。

目前看是不知道为啥 kotlin 不返回 inlay 消息， 如果返回， lsp-bridge 应该像 rust 那样默认就支持。

**Comment by getong** [comment]
```
git clone https://github.com/fwcd/kotlin-language-server
cd kotlin-language-server

git diff  server/src/main/kotlin/org/javacs/kt/Configuration.kt

index 5fb9fb4..f05ffd2 100644
--- a/server/src/main/kotlin/org/javacs/kt/Configuration.kt
+++ b/server/src/main/kotlin/org/javacs/kt/Configuration.kt
@@ -47,9 +47,9 @@ public data class ExternalSourcesConfiguration(
 )
 
 data class InlayHintsConfiguration(
-    var typeHints: Boolean = false,
-    var parameterHints: Boolean = false,
-    var chainedHints: Boolean = false
+    var typeHints: Boolean = true,
+    var parameterHints: Boolean = true,
+    var chainedHints: Boolean = true
 )

./gradlew :server:installDist -PjavaVersion=11

export PATH=$PWD/server/build/install/server/bin:$PATH
```

**Comment by getong** [comment]
我看这个pr,  https://github.com/emacs-lsp/lsp-mode/pull/4197/files
它设置了
```
("kotlin.inlayHints.typeHints" lsp-kotlin-inlayhints-enable-typehints t)
("kotlin.inlayHints.parameterHints" lsp-kotlin-inlayhints-enable-parameterhints t)
("kotlin.inlayHints.chainedHints" lsp-kotlin-inlayhints-enable-chainedhints t))
```
我已经提交配置到lsp-bridge里面了，但不知道lsp-mode的设置方法跟lsp-bridge是否一致？

**Comment by manateelazycat** [comment]
> ```
> git clone https://github.com/fwcd/kotlin-language-server
> cd kotlin-language-server
> 
> git diff  server/src/main/kotlin/org/javacs/kt/Configuration.kt
> 
> index 5fb9fb4..f05ffd2 100644
> --- a/server/src/main/kotlin/org/javacs/kt/Configuration.kt
> +++ b/server/src/main/kotlin/org/javacs/kt/Configuration.kt
> @@ -47,9 +47,9 @@ public data class ExternalSourcesConfiguration(
>  )
>  
>  data class InlayHintsConfiguration(
> -    var typeHints: Boolean = false,
> -    var parameterHints: Boolean = false,
> -    var chainedHints: Boolean = false
> +    var typeHints: Boolean = true,
> +    var parameterHints: Boolean = true,
> +    var chainedHints: Boolean = true
>  )
> 
> ./gradlew :server:installDist -PjavaVersion=11
> 
> export PATH=$PWD/server/build/install/server/bin:$PATH
> ```

这个有用吗？

**Comment by getong** [comment]
这个开启kotlin-language-server的inlayhint提示，强制开启。而不是通过客户端设置开始。

**Comment by manateelazycat** [comment]
我的意思是你开启这样以后，它会返回消息给lsp-bridge吗

**Comment by getong** [comment]
这个我不确定。但我确定lsp-mode有返回消息。

**Comment by getong** [comment]
![Uploading kotlin-language-server.jpg…]()
有效果了，看起来挺好的。

**Comment by getong** [comment]
#778 已经配置好kotlin的配置文件了，我在macos是可以从emacs客户端开启inlayhint特性的，这个是从lsp-mode参考得来的。
