### ISSUE TITLE
出现这个错误后TypeError: SearchFileWords.change_buffer() takes 5 positional arguments but 6 were given无法使用

### ISSUE THREAD

**Issue by sweet66** [manateelazycat/lsp-bridge#802]
ERROR:epc:TypeError('SearchFileWords.change_buffer() takes 5 positional arguments but 6 were given')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/Users/xxx/.local/lib/python3.11/site-packages/epc/handler.py", line 242, in _handle
    reply = handler(uid, *args)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/lib/python3.11/site-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/lib/python3.11/site-packages/epc/handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
                           ^^^^^^^^^^^
  File "/Users/xxx/.emacs.d/site-lisp/extensions/lsp-bridge/lsp_bridge.py", line 797, in _do
    getattr(getattr(self, obj_name), name)(*args, **kwargs)

**Comment by manateelazycat** [comment]
有重现步骤和重现文件吗

**Comment by manateelazycat** [comment]
If you byte compile lsp-bridge, please remove byte compile file and disable byte compile

**Comment by sweet66** [comment]
打开一个ts文件，输入"import" 关键字 就会报这个错误。emacs版本是GNU Emacs 28.2 (build 1, x86_64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.5 (Build 21G531)) of 2023-11-24

**Comment by sweet66** [comment]
解决了，用源码编译的emacs是正常的，之前用的是emacs-plus。

**Comment by sweet66** [comment]
还是出现了，是在不同文件buffer之间切换会出现，例如打开一个el文件输入内容，然后再打开一个ts文件输入内容进行代码补全，然后再切换buffer到之前的el文件输入内容就会出现

**Comment by manateelazycat** [comment]
最好 emacs -Q 对比测试一下， 避免其他插件配置干扰
