### ISSUE TITLE
执行 lsp-bridge-workspace-list-symbols 报错

### ISSUE THREAD

**Issue by bbenchen** [manateelazycat/lsp-bridge#881]
Traceback (most recent call last):
  File "/Users/xianbin/Projects/emacs/lsp-bridge/lsp_bridge.py", line 515, in event_dispatcher
    getattr(self, func_name)(*func_args)
  File "/Users/xianbin/Projects/emacs/lsp-bridge/lsp_bridge.py", line 776, in _do
    action.call(name, *args)
  File "/Users/xianbin/Projects/emacs/lsp-bridge/core/fileaction.py", line 163, in call
    self.send_request(method_server, method, handler, *args, **kwargs)
  File "/Users/xianbin/Projects/emacs/lsp-bridge/core/fileaction.py", line 170, in send_request
    self.send_server_request(method_server, method, *args, **kwargs)
  File "/Users/xianbin/Projects/emacs/lsp-bridge/core/fileaction.py", line 437, in send_server_request
    params = handler.process_request(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WorkspaceSymbol.process_request() takes 2 positional arguments but 3 were given

ERROR:epc:handle_error: trying to get traceback.format_exc
ERROR:epc:handle_error: 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/Users/xianbin/Library/Python/3.12/lib/python/site-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xianbin/Library/Python/3.12/lib/python/site-packages/epc/handler.py", line 232, in handle
    self._handle(sexp)
  File "/Users/xianbin/Library/Python/3.12/lib/python/site-packages/epc/handler.py", line 414, in _handle
    newthread(self, target=EPCHandler._handle, args=(self, sexp)).start()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

**Comment by manateelazycat** [comment]
Please give test code

**Comment by bbenchen** [comment]
@manateelazycat

**Comment by bbenchen** [comment]
找到原因了，`(interactive "sWorkspace symbol query: ")` 函数返回的不是纯粹的字符，而是被包装过的
如我输入kkkk，它的结果是`(#("kkkk" 0 4 (ws-butler-chg chg)))`，
不清楚为什么会这样

**Comment by bbenchen** [comment]
是 `ws-butler` 插件引起的，关闭它就可以了
