### ISSUE TITLE
Trigger `IMPOSSIBLE HERE: handle_server_message`

### ISSUE THREAD

**Issue by zy9306** [manateelazycat/lsp-bridge#89]
日志可能不完整了，正常干活，突然没补全了，目前我也不清楚我做了啥，先贴上来吧
```
Exit server: /nix/store/1kxvwk77952rppirjn258z7s3i3680zx-go-1.16/share/go/src/strings/strings.go#gopls

--- Recv notification: window/logMessage

--- Recv notification: window/logMessage

--- Recv response (37146): textDocument/signatureHelp

--- Recv message (error):
{
   "jsonrpc": "2.0",
   "error": {
      "code": -32602,
      "message": "JSON RPC invalid params: expected no params: JSON RPC invalid params"
   },
   "id": 57852
}
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
gopls: remote disconnected: <nil>
  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/zy/.emacs.d/repo/lsp-bridge/lsp-bridge.py", line 110, in message_dispatcher
    self.handle_server_message(*message["content"])
  File "/Users/zy/.emacs.d/repo/lsp-bridge/lsp-bridge.py", line 198, in handle_server_message
    logger.error("IMPOSSIBLE HERE: handle_server_message %s %s", filepath, request_type, request_id, response_result)
Message: 'IMPOSSIBLE HERE: handle_server_message %s %s'
Arguments: ('/nix/store/1kxvwk77952rppirjn258z7s3i3680zx-go-1.16/share/go/src/strings/strings.go', 'signature_help', 37146, None)

--- Recv notification: window/logMessage

--- Lsp server exited, exit code: 2
b''
gopls: remote disconnected: <nil>

--- Lsp server exited, exit code: 2
b''
```

**Comment by manateelazycat** [comment]
参数日志的错误 https://github.com/manateelazycat/lsp-bridge/commit/7c5417abd14b296d122928635eafa426c92059b9 这个补丁修复了。

你的问题看着像 signature_help 消息在 close_file 这个消息以后发出去的，导致 file_action_dict 找不到文件对应的内容。

@zerolfx 正在解决请求顺序的 bug, 等他推送完以后再测试一遍吧。

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/lsp-bridge/pull/93
