### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by jenenliu** [manateelazycat/lsp-bridge#913]
Archlinux with rbenv, ruby version 3.2.2
It seems not works for lsp-bridge, only search word pop up on completion menu.
And I get this error, is it bug, or just configuration issue ?
![image](https://github.com/manateelazycat/lsp-bridge/assets/5833520/e32c1dbb-0eb4-42f1-9d0d-5a2752f88abc)

```
--- [22:00:59.731850] Recv textDocument/completion response (30879) from 'solargraph' for project best_cat
Error when processing response 30879
Traceback (most recent call last):
  File "/home/jenenliu/lazycat-emacs/site-lisp/extensions/lspbridge/core/handler/__init__.py", line 38, in handle_response
    self.process_response(response)
  File "/home/jenenliu/lazycat-emacs/site-lisp/extensions/lspbridge/core/handler/completion.py", line 152, in process_response
    "displayLabel": self.get_display_label(item, display_new_text),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenenliu/lazycat-emacs/site-lisp/extensions/lspbridge/core/handler/completion.py", line 78, in get_display_label
    if detail.strip() != "":
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```

Thanks a lot.

**Comment by manateelazycat** [comment]
I have push https://github.com/manateelazycat/lsp-bridge/commit/c59aaf65e27c12ac4f45e11dd83ac75c2d5c46aa

Please update and try agian, thanks. ;)

**Comment by manateelazycat** [comment]
@jenenliu Please re-open this issue if newest version still have problem.

**Comment by jenenliu** [comment]
@manateelazycat it works now, thanks a lot!
